import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsCA: VocabSetRaw = [
  [
    "l'aigua",
    "Sempre és important beure molta aigua.",
    "commonNouns/water.jpeg",
    "/ajɣwə/",
    { 32: 38 },
  ],
  [
    "l'ampolla",
    "La meva ampolla d'aigua està sempre a la meva motxilla.",
    "commonNouns/bottle.jpeg",
    "/əmˈpɔʎə/",
    { 8: 15 },
  ],
  [
    "l'arbre",
    "Aquest arbre ha estat aquí des de fa més de cent anys.",
    "commonNouns/tree.jpeg",
    "/ˈarβɾə/",
    { 7: 12 },
  ],
  [
    "l'avió",
    "Volant alt en el cel, es pot veure l'avió.",
    "commonNouns/airplane.jpeg",
    "/əβiˈo/",
    { 35: 42 },
  ],
  [
    "la bicicleta",
    "Estic pensant a comprar una bicicleta nova.",
    "commonNouns/bicycle.jpeg",
    "/bisiˈklɛtə/",
    { 28: 37 },
  ],
  [
    "la barca",
    "Estic remant una barca en el riu.",
    "commonNouns/boat.jpeg",
    "/ˈbaɾkə/",
    { 17: 22 },
  ],
  [
    "el bosc",
    "Ens hem perdut al bosc durant una estona.",
    "commonNouns/forest.jpeg",
    "/ˈbɔsk/",
    { 18: 22 },
  ],
  [
    "la cadira",
    "Aquella cadira antiga té una història interessant.",
    "commonNouns/chair.jpeg",
    "/kəˈðiɾə/",
    { 8: 14 },
  ],
  [
    "la càmera",
    "Estic carregant la càmera per a la sortida de demà.",
    "commonNouns/camera.jpeg",
    "/ˈkaməɾə/",
    { 16: 18, 19: 25 },
  ],
  [
    "la carretera",
    "Estem conduint per una carretera secundària.",
    "commonNouns/road.jpeg",
    "/kərəˈtɛɾə/",
    { 23: 32 },
  ],
  [
    "la casa",
    "La casa on vaig créixer està plena de records.",
    "commonNouns/house.jpeg",
    "/ˈkazə/",
    { 0: 2, 3: 7 },
  ],
  [
    "el cel",
    "El cel està ple d'estrelles aquesta nit.",
    "commonNouns/sky.jpeg",
    "/ˈsɛl/",
    { 0: 2, 3: 6 },
  ],
  [
    "la clau",
    "Necessito la clau per a obrir la porta.",
    "commonNouns/key.jpeg",
    "/ˈklaw/",
    { 10: 12, 13: 17 },
  ],
  [
    "el cotxe",
    "El cotxe que sempre he volgut és de color blau.",
    "commonNouns/car.jpeg",
    "/ˈkɔtʃə/",
    { 0: 2, 3: 8 },
  ],
  [
    "els diners",
    "Els diners no fan la felicitat, però ajuden.",
    "commonNouns/money.jpeg",
    "/ˈdinərs/",
    { 0: 3, 4: 10 },
  ],
  [
    "la finestra",
    "La finestra dóna al jardí i té unes vistes precioses.",
    "commonNouns/window.jpeg",
    "/finˈɛstɾə/",
    { 0: 2, 3: 11 },
  ],
  [
    "la flor",
    "La flor que estàs olorant té un aroma molt agradable.",
    "commonNouns/flower.jpeg",
    "/ˈfloɾ/",
    { 0: 2, 3: 7 },
  ],
  [
    "la fotografia",
    "Aquella fotografia que mires és del meu avi.",
    "commonNouns/photograph.jpeg",
    "/futuɣɾaˈfi.ə/",
    { 8: 18 },
  ],
  [
    "el gos",
    "El gos està jugant amb la seva pilota a la platja.",
    "commonNouns/dog.jpeg",
    "/ˈɡɔs/",
    { 0: 2, 3: 6 },
  ],
  [
    "el got",
    "Et puc servir més suc en el teu got?",
    "commonNouns/glass.jpeg",
    "/ˈɡɔt/",
    { 25: 27, 32: 36 },
  ],
  [
    "el gat",
    "Aquell gat negre sembla una mica espantat.",
    "commonNouns/cat.jpeg",
    "/ˈɡat/",
    { 7: 10 },
  ],
  [
    "la granja",
    "Aquella granja on vaig anar de petit tenia molts animals.",
    "commonNouns/farm.jpeg",
    "/ˈɡɾanʒə/",
    { 8: 14 },
  ],
  [
    "l'herba",
    "M'agrada sentir l'herba sota els meus peus descalços.",
    "commonNouns/grass.jpeg",
    "/ˈɛrβə/",
    { 16: 23 },
  ],
  [
    "el jardí",
    "El jardí de la meva àvia està ple de flors colorides.",
    "commonNouns/garden.jpeg",
    "/ʒərˈdi/",
    { 0: 2, 3: 8 },
  ],
  [
    "el llapis",
    "Estic escrivint amb un llapis nou.",
    "commonNouns/pencil.jpeg",
    "/ʎəˈpis/",
    { 23: 29 },
  ],
  [
    "el llibre",
    "Acabo de llegir un capítol d'un llibre interessant.",
    "commonNouns/book.jpeg",
    "/ʎiˈβɾə/",
    { 32: 38 },
  ],
  [
    "el llit",
    "Després d'un llarg dia, el llit sembla molt convidant.",
    "commonNouns/bed.jpeg",
    "/ʎit/",
    { 24: 26, 27: 31 },
  ],
  [
    "la llum",
    "La llum del sol entra per la finestra.",
    "commonNouns/light.jpeg",
    "/ʎum/",
    { 0: 2, 3: 7 },
  ],
  [
    "la lluna",
    "La lluna brilla amb força aquesta nit.",
    "commonNouns/moon.jpeg",
    "/ʎunə/",
    { 0: 2, 3: 8 },
  ],
  [
    "la mà",
    "La mà de la meva àvia té les arrugues de l'experiència.",
    "commonNouns/hand.jpeg",
    "/ˈma/",
    { 0: 2, 3: 5 },
  ],
  [
    "el menjar",
    "El menjar que he preparat avui ha quedat molt gustós.",
    "commonNouns/food.jpeg",
    "/mənˈʒaɾ/",
    { 0: 2, 3: 9 },
  ],
  [
    "la muntanya",
    "La muntanya que veus al fons és el Montserrat.",
    "commonNouns/mountain.jpeg",
    "/munˈtaɲə/",
    { 0: 2, 3: 11 },
  ],
  [
    "el nadó",
    "Somrient, el nadó juga amb el seu joguet.",
    "commonNouns/baby.jpeg",
    "/nəˈdo/",
    { 10: 12, 13: 17 },
  ],
  [
    "l'ordinador",
    "Estic treballant en un projecte al meu ordinador.",
    "commonNouns/computer.jpeg",
    "/ɔrðiˈnaðoɾ/",
    { 39: 49 },
  ],
  [
    "l'ocell",
    "Escolto l'ocell que canta des de l'arbre.",
    "commonNouns/bird.jpeg",
    "/uˈsɛʎ/",
    { 8: 15 },
  ],
  [
    "el pa",
    "Aquest pa acabat de sortir del forn és deliciós.",
    "commonNouns/bread.jpeg",
    "/ˈpa/",
    { 7: 9 },
  ],
  [
    "el paper",
    "Estic plegant un avió de paper.",
    "commonNouns/paper.jpeg",
    "/pəˈpe/",
    { 25: 31 },
  ],
  [
    "el peix",
    "Aquest peix que estic menjant és realment deliciós.",
    "commonNouns/fish.jpeg",
    "/ˈpeʃ/",
    { 7: 11 },
  ],
  [
    "la pilota",
    "El nen està xutant la pilota.",
    "commonNouns/ball.jpeg",
    "/piˈlotə/",
    { 19: 21, 22: 29 },
  ],
  [
    "la platja",
    "Molta gent gaudeix del sol a la platja.",
    "commonNouns/beach.jpeg",
    "/ˈplatʒə/",
    { 29: 31, 32: 39 },
  ],
  [
    "el plat",
    "Aquell plat que estàs netejant és molt antic.",
    "commonNouns/plate.jpeg",
    "/ˈplat/",
    { 7: 11 },
  ],
  [
    "la porta",
    "Està trucant a la porta, potser és el carter.",
    "commonNouns/door.jpeg",
    "/ˈportə/",
    { 15: 17, 18: 24 },
  ],
  [
    "la roba",
    "La roba que vaig comprar ahir és molt còmoda.",
    "commonNouns/clothes.jpeg",
    "/ˈrobə/",
    { 0: 2, 3: 7 },
  ],
  [
    "el riu",
    "El riu flueix tranquil·lament a través del bosc.",
    "commonNouns/river.jpeg",
    "/ˈriw/",
    { 0: 2, 3: 6 },
  ],
  [
    "el rellotge",
    "Em van regalar aquest rellotge el dia del meu aniversari.",
    "commonNouns/clock.jpeg",
    "/rəˈʎɔtʒə/",
    { 22: 30 },
  ],
  [
    "el rellotge (de polsera)",
    "Em vaig posar el rellotge de polsera abans de sortir de casa.",
    "commonNouns/watch.jpeg",
    "/rəˈʎɔtʒə (də polˈsɛɾə)/",
    { 14: 16, 17: 25, 26: 28, 29: 36 },
  ],
  [
    "la sabata",
    "Aquella sabata que estàs veient és de la meva talla.",
    "commonNouns/shoe.jpeg",
    "/səˈbatə/",
    { 8: 14 },
  ],
  [
    "la taula",
    "La taula on estem sopant és de fusta de pi.",
    "commonNouns/table.jpeg",
    "/ˈtawɫə/",
    { 0: 2, 3: 8 },
  ],
  [
    "el telèfon",
    "Em pots passar el telèfon, si us plau?",
    "commonNouns/phone.jpeg",
    "/təˈlɛfun/",
    { 15: 17, 18: 26 },
  ],
  [
    "el tren",
    "Estem esperant el tren a l'estació.",
    "commonNouns/train.jpeg",
    "/ˈtɾɛn/",
    { 15: 17, 18: 22 },
  ],
];
