import { initialVocabProperties } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";
import { v4 as uuid4 } from "uuid";

export const commonNounsCA: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "l'aigua",
      "Sempre és important beure molta aigua.",
      "water.jpeg",
      "/lˈajɣwə/",
      { 32: 38 },
    ],
    [
      "l'ampolla",
      "La meva ampolla d'aigua està sempre a la meva motxilla.",
      "bottle.jpeg",
      "/ləmˈpɔʎə/",
      { 8: 15 },
    ],
    [
      "l'arbre",
      "Aquest arbre ha estat aquí des de fa més de cent anys.",
      "tree.jpeg",
      "/ˈlarβɾə/",
      { 7: 12 },
    ],
    [
      "l'avió",
      "Volant alt en el cel, es pot veure l'avió.",
      "airplane.jpeg",
      "/ləβiˈo/",
      { 35: 42 },
    ],
    [
      "la bicicleta",
      "Estic pensant a comprar una bicicleta nova.",
      "bicycle.jpeg",
      "/bisiˈklɛtə/",
      { 28: 37 },
    ],
    [
      "la barca",
      "Estic remant una barca en el riu.",
      "boat.jpeg",
      "/ˈbaɾkə/",
      { 17: 22 },
    ],
    [
      "el bosc",
      "Ens hem perdut al bosc durant una estona.",
      "forest.jpeg",
      "/ˈbɔsk/",
      { 18: 22 },
    ],
    [
      "la cadira",
      "Aquella cadira antiga té una història interessant.",
      "chair.jpeg",
      "/kəˈðiɾə/",
      { 8: 14 },
    ],
    [
      "la càmera",
      "Estic carregant la càmera per a la sortida de demà.",
      "camera.jpeg",
      "/ˈkaməɾə/",
      { 16: 18, 19: 25 },
    ],
    [
      "la carretera",
      "Estem conduint per una carretera secundària.",
      "road.jpeg",
      "/kərəˈtɛɾə/",
      { 23: 32 },
    ],
    [
      "la casa",
      "La casa on vaig créixer està plena de records.",
      "house.jpeg",
      "/ˈkazə/",
      { 0: 2, 3: 7 },
    ],
    [
      "el cel",
      "El cel està ple d'estrelles aquesta nit.",
      "sky.jpeg",
      "/ˈsɛl/",
      { 0: 2, 3: 6 },
    ],
    [
      "la clau",
      "Necessito la clau per a obrir la porta.",
      "key.jpeg",
      "/ˈklaw/",
      { 10: 12, 13: 17 },
    ],
    [
      "el cotxe",
      "El cotxe que sempre he volgut és de color blau.",
      "car.jpeg",
      "/ˈkɔtʃə/",
      { 0: 2, 3: 8 },
    ],
    [
      "els diners",
      "Els diners no fan la felicitat, però ajuden.",
      "money.jpeg",
      "/ˈdinərs/",
      { 0: 3, 4: 10 },
    ],
    [
      "la finestra",
      "La finestra dóna al jardí i té unes vistes precioses.",
      "window.jpeg",
      "/finˈɛstɾə/",
      { 0: 2, 3: 11 },
    ],
    [
      "la flor",
      "La flor que estàs olorant té un aroma molt agradable.",
      "flower.jpeg",
      "/ˈfloɾ/",
      { 0: 2, 3: 7 },
    ],
    [
      "la fotografia",
      "Aquella fotografia que mires és del meu avi.",
      "photograph.jpeg",
      "/futuɣɾaˈfi.ə/",
      { 8: 18 },
    ],
    [
      "el gos",
      "El gos està jugant amb la seva pilota a la platja.",
      "dog.jpeg",
      "/ˈɡɔs/",
      { 0: 2, 3: 6 },
    ],
    [
      "el got",
      "Et puc servir més suc en el teu got?",
      "glass.jpeg",
      "/ˈɡɔt/",
      { 25: 27, 32: 36 },
    ],
    [
      "el gat",
      "Aquell gat negre sembla una mica espantat.",
      "cat.jpeg",
      "/ˈɡat/",
      { 7: 10 },
    ],
    [
      "la granja",
      "Aquella granja on vaig anar de petit tenia molts animals.",
      "farm.jpeg",
      "/ˈɡɾanʒə/",
      { 8: 14 },
    ],
    [
      "l'herba",
      "M'agrada sentir l'herba sota els meus peus descalços.",
      "grass.jpeg",
      "/ˈlɛrβə/",
      { 16: 23 },
    ],
    [
      "el jardí",
      "El jardí de la meva àvia està ple de flors colorides.",
      "garden.jpeg",
      "/ʒərˈdi/",
      { 0: 2, 3: 8 },
    ],
    [
      "el llapis",
      "Estic escrivint amb un llapis nou.",
      "pencil.jpeg",
      "/ʎəˈpis/",
      { 23: 29 },
    ],
    [
      "el llibre",
      "Acabo de llegir un capítol d'un llibre interessant.",
      "book.jpeg",
      "/ʎiˈβɾə/",
      { 32: 38 },
    ],
    [
      "el llit",
      "Després d'un llarg dia, el llit sembla molt convidant.",
      "bed.jpeg",
      "/ʎit/",
      { 24: 26, 27: 31 },
    ],
    [
      "la llum",
      "La llum del sol entra per la finestra.",
      "light.jpeg",
      "/ʎum/",
      { 0: 2, 3: 7 },
    ],
    [
      "la lluna",
      "La lluna brilla amb força aquesta nit.",
      "moon.jpeg",
      "/ʎunə/",
      { 0: 2, 3: 8 },
    ],
    [
      "la mà",
      "La mà de la meva àvia té les arrugues de l'experiència.",
      "hand.jpeg",
      "/ˈma/",
      { 0: 2, 3: 5 },
    ],
    [
      "el menjar",
      "El menjar que he preparat avui ha quedat molt gustós.",
      "food.jpeg",
      "/mənˈʒaɾ/",
      { 0: 2, 3: 9 },
    ],
    [
      "la muntanya",
      "La muntanya que veus al fons és el Montserrat.",
      "mountain.jpeg",
      "/munˈtaɲə/",
      { 0: 2, 3: 11 },
    ],
    [
      "el nadó",
      "Somrient, el nadó juga amb el seu joguet.",
      "baby.jpeg",
      "/nəˈdo/",
      { 10: 12, 13: 17 },
    ],
    [
      "l'ordinador",
      "Estic treballant en un projecte al meu ordinador.",
      "computer.jpeg",
      "/lˌɔrðiˈnaðoɾ/",
      { 39: 49 },
    ],
    [
      "l'ocell",
      "Escolto l'ocell que canta des de l'arbre.",
      "bird.jpeg",
      "/uˈsɛʎ/",
      { 8: 15 },
    ],
    [
      "el pa",
      "Aquest pa acabat de sortir del forn és deliciós.",
      "bread.jpeg",
      "/ˈpa/",
      { 7: 9 },
    ],
    [
      "el paper",
      "Estic plegant un avió de paper.",
      "paper.jpeg",
      "/pəˈpe/",
      { 25: 31 },
    ],
    [
      "el peix",
      "Aquest peix que estic menjant és realment deliciós.",
      "fish.jpeg",
      "/ˈpeʃ/",
      { 7: 11 },
    ],
    [
      "la pilota",
      "El nen està xutant la pilota.",
      "ball.jpeg",
      "/piˈlotə/",
      { 19: 21, 22: 29 },
    ],
    [
      "la platja",
      "Molta gent gaudeix del sol a la platja.",
      "beach.jpeg",
      "/ˈplatʒə/",
      { 29: 31, 32: 39 },
    ],
    [
      "el plat",
      "Aquell plat que estàs netejant és molt antic.",
      "plate.jpeg",
      "/ˈplat/",
      { 7: 11 },
    ],
    [
      "la porta",
      "Està trucant a la porta, potser és el carter.",
      "door.jpeg",
      "/ˈportə/",
      { 15: 17, 18: 24 },
    ],
    [
      "la roba",
      "La roba que vaig comprar ahir és molt còmoda.",
      "clothes.jpeg",
      "/ˈrobə/",
      { 0: 2, 3: 7 },
    ],
    [
      "el riu",
      "El riu flueix tranquil·lament a través del bosc.",
      "river.jpeg",
      "/ˈriw/",
      { 0: 2, 3: 6 },
    ],
    [
      "el rellotge",
      "Em van regalar aquest rellotge el dia del meu aniversari.",
      "clock.jpeg",
      "/rəˈʎɔtʒə/",
      { 22: 30 },
    ],
    [
      "el rellotge (de polsera)",
      "Em vaig posar el rellotge de polsera abans de sortir de casa.",
      "watch.jpeg",
      "/rəˈʎɔtʒə (də polˈsɛɾə)/",
      { 14: 16, 17: 25, 26: 28, 29: 36 },
    ],
    [
      "la sabata",
      "Aquella sabata que estàs veient és de la meva talla.",
      "shoe.jpeg",
      "/səˈbatə/",
      { 8: 14 },
    ],
    [
      "la taula",
      "La taula on estem sopant és de fusta de pi.",
      "table.jpeg",
      "/ˈtawɫə/",
      { 0: 2, 3: 8 },
    ],
    [
      "el telèfon",
      "Em pots passar el telèfon, si us plau?",
      "phone.jpeg",
      "/təˈlɛfun/",
      { 15: 17, 18: 26 },
    ],
    [
      "el tren",
      "Estem esperant el tren a l'estació.",
      "train.jpeg",
      "/ˈtɾɛn/",
      { 15: 17, 18: 22 },
    ],
  ];

for (let i = 0; i < vocabEntries.length; i++) {
  const id = uuid4();

  commonNounsCA[id] = {
    vocabId: id,
    blackoutWords: vocabEntries[i][4],
    category: "noun",
    definition: vocabEntries[i][0],
    description: vocabEntries[i][1],
    imageURL: "/images/vocabSets/commonNouns/" + vocabEntries[i][2],
    ...initialVocabProperties,
    phoneticPronunciation: vocabEntries[i][3],
  };
}
