import { generateVocabSet } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";

export const commonNounsDE: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "das Flugzeug",
      "Hoch über den Wolken flog das Flugzeug.",
      "airplane.jpeg",
      "/ˈfluːktsɔʏk/",
      { 26: 29, 30: 39 },
    ],
    [
      "das Baby",
      "Das Baby lächelte ihrer Mutter zu.",
      "baby.jpeg",
      "/ˈbeːbi/",
      { 0: 3, 4: 8 },
    ],
    [
      "der Ball",
      "John trat den Ball in Richtung Tor.",
      "ball.jpeg",
      "/baːl/",
      { 14: 18 },
    ],
    [
      "der Strand",
      "Wir planen, den Tag am Strand zu verbringen.",
      "beach.jpeg",
      "/ʃtʁant/",
      { 23: 29 },
    ],
    [
      "das Bett",
      "Erschöpft vom Tag legte sie sich auf ihr Bett.",
      "bed.jpeg",
      "/bɛt/",
      { 41: 46 },
    ],
    [
      "das Fahrrad",
      "Er fuhr mit dem Fahrrad um den Park.",
      "bicycle.jpeg",
      "/ˈfaːʁaːt/",
      { 16: 23 },
    ],
    [
      "der Vogel",
      "Vom Baum aus sang der Vogel wunderschön.",
      "bird.jpeg",
      "/ˈfoːgəl/",
      { 18: 21, 22: 27 },
    ],
    [
      "das Boot",
      "Sie segelten den Fluss mit dem Boot hinunter.",
      "boat.jpeg",
      "/boːt/",
      { 31: 35 },
    ],
    [
      "das Buch",
      "Sie öffnete das Buch und fing an zu lesen.",
      "book.jpeg",
      "/buːx/",
      { 12: 15, 16: 20 },
    ],
    [
      "die Flasche",
      "Ich füllte die Flasche mit frischem Quellwasser.",
      "bottle.jpeg",
      "/ˈflaʃə/",
      { 11: 14, 15: 22 },
    ],
    [
      "das Brot",
      "Sie schnitt das Brot zum Frühstück.",
      "bread.jpeg",
      "/bʁoːt/",
      { 12: 15, 16: 20 },
    ],
    [
      "die Kamera",
      "Mit seiner Kamera machte er ein Bild der schönen Landschaft.",
      "camera.jpeg",
      "/kaˈmeːʁa/",
      { 11: 17 },
    ],
    [
      "das Auto",
      "Auf dem Weg ins Büro ging das Auto kaputt.",
      "car.jpeg",
      "/ˈaʊ̯toː/",
      { 26: 29, 30: 34 },
    ],
    [
      "die Katze",
      "Auf dem Sofa schlief die Katze.",
      "cat.jpeg",
      "/ˈkatsə/",
      { 21: 24, 25: 31 },
    ],
    [
      "der Stuhl",
      "Er zog den Stuhl hervor und setzte sich.",
      "chair.jpeg",
      "/ʃtuːl/",
      { 11: 16 },
    ],
    [
      "die Uhr",
      "Die Uhr schlug Mitternacht.",
      "clock.jpeg",
      "/ʊʁ/",
      { 0: 3, 4: 7 },
    ],
    [
      "die Kleidung",
      "Sie faltete die Kleidung und räumte sie weg.",
      "clothes.jpeg",
      "/ˈklaɪ̯dʊŋ/",
      { 12: 15, 16: 24 },
    ],
    [
      "der Computer",
      "Um mit seiner Arbeit zu beginnen, schaltete er den Computer ein.",
      "computer.jpeg",
      "/kɔmˈpuːtɐ/",
      { 51: 59 },
    ],
    [
      "der Hund",
      "Der Hund wedelte fröhlich mit dem Schwanz.",
      "dog.jpeg",
      "/hʊnt/",
      { 0: 3, 4: 8 },
    ],
    [
      "die Tür",
      "Er klopfte an die Tür.",
      "door.jpeg",
      "/tyːɐ̯/",
      { 14: 17, 18: 22 },
    ],
    [
      "der Bauernhof",
      "Sie verbrachten den Tag mit Arbeiten auf dem Bauernhof.",
      "farm.jpeg",
      "/ˈbaʊ̯ɐnhoːf/",
      { 45: 55 },
    ],
    [
      "der Fisch",
      "In klarem Wasser schwamm der Fisch schnell.",
      "fish.jpeg",
      "/fɪʃ/",
      { 25: 28, 29: 34 },
    ],
    [
      "die Blume",
      "Die Blume blühte wunderschön im Garten.",
      "flower.jpeg",
      "/ˈbluːmə/",
      { 0: 3, 4: 9 },
    ],
    [
      "das Essen",
      "Das Essen roch köstlich.",
      "food.jpeg",
      "/ˈɛsn̩/",
      { 0: 3, 4: 9 },
    ],
    ["der Wald", "Sie wanderten im Wald.", "forest.jpeg", "/valt/", { 17: 22 }],
    [
      "der Garten",
      "Im Garten jätete sie Unkraut.",
      "garden.jpeg",
      "/ˈɡaʁtn̩/",
      { 3: 9 },
    ],
    [
      "das Glas",
      "Er füllte sein Glas mit Saft.",
      "glass.jpeg",
      "/ɡlaːs/",
      { 15: 19 },
    ],
    [
      "das Gras",
      "Die Kinder spielten im Gras.",
      "grass.jpeg",
      "/ɡʁaːs/",
      { 23: 28 },
    ],
    [
      "die Hand",
      "Die Hand des Babys hielt sie sanft.",
      "hand.jpeg",
      "/hant/",
      { 0: 3, 4: 8 },
    ],
    ["das Haus", "Das Haus war still.", "house.jpeg", "/haʊ̯s/", { 0: 3, 4: 8 }],
    [
      "der Schlüssel",
      "Er verlor den Schlüssel zu seinem Auto.",
      "key.jpeg",
      "/ˈʃlʏsl̩/",
      { 14: 23 },
    ],
    [
      "das Licht",
      "Durch das Fenster kam Licht herein.",
      "light.jpeg",
      "/lɪçt/",
      { 22: 27 },
    ],
    [
      "das Geld",
      "Er sparte so viel Geld wie möglich.",
      "money.jpeg",
      "/ɡɛlt/",
      { 18: 22 },
    ],
    [
      "der Mond",
      "Hell schien der Mond am Nachthimmel.",
      "moon.jpeg",
      "/moːnt/",
      { 12: 15, 16: 20 },
    ],
    [
      "der Berg",
      "Zusammen bestiegen sie den Berg.",
      "mountain.jpeg",
      "/bɛʁk/",
      { 27: 32 },
    ],
    [
      "das Papier",
      "Auf dem Papier schrieb er eine Notiz.",
      "paper.jpeg",
      "/paˈpiːɐ̯/",
      { 8: 14 },
    ],
    [
      "der Bleistift",
      "Bevor sie mit ihrer Zeichnung begann, spitzte sie ihren Bleistift.",
      "pencil.jpeg",
      "/ˈblaɪ̯ʃtɪft/",
      { 56: 66 },
    ],
    [
      "das Telefon",
      "Mitten in der Nacht klingelte das Telefon.",
      "phone.jpeg",
      "/teleˈfoːn/",
      { 30: 33, 34: 42 },
    ],
    [
      "das Foto",
      "Das Foto weckte viele Erinnerungen.",
      "photograph.jpeg",
      "/ˈfoːto/",
      { 0: 3, 4: 8 },
    ],
    [
      "der Teller",
      "Er wusch den Teller und stellte ihn zurück ins Regal.",
      "plate.jpeg",
      "/ˈtɛlɐ/",
      { 13: 19 },
    ],
    [
      "der Fluss",
      "Sie folgten dem Fluss, bis sie ein kleines Dorf erreichten.",
      "river.jpeg",
      "/flʊs/",
      { 16: 22 },
    ],
    [
      "die Straße",
      "Die Straße war holprig und voller Schlaglöcher.",
      "road.jpeg",
      "/ˈʃtʁaːsə/",
      { 0: 3, 4: 10 },
    ],
    [
      "der Schuh",
      "Er band die Schnürsenkel seines Schuhs.",
      "shoe.jpeg",
      "/ʃuː/",
      { 32: 39 },
    ],
    [
      "der Himmel",
      "Der Himmel war voller Wolken.",
      "sky.jpeg",
      "/ˈhɪml̩/",
      { 0: 3, 4: 10 },
    ],
    [
      "der Tisch",
      "Sie deckte den Tisch für das Abendessen.",
      "table.jpeg",
      "/tɪʃ/",
      { 15: 20 },
    ],
    [
      "der Zug",
      "Der Zug erreichte pünktlich den Bahnhof.",
      "train.jpeg",
      "/tsuːk/",
      { 0: 3, 4: 7 },
    ],
    [
      "der Baum",
      "Der Baum spendete Schatten in der heißen Sonne.",
      "tree.jpeg",
      "/baʊ̯m/",
      { 0: 3, 4: 8 },
    ],
    [
      "die Armbanduhr",
      "Er sah auf seine Armbanduhr und stellte fest, dass er spät dran war.",
      "watch.jpeg",
      "/ʊʁ/",
      { 17: 27 },
    ],
    [
      "das Wasser",
      "Das Wasser trank sie schnell.",
      "water.jpeg",
      "/ˈvasɐ/",
      { 0: 3, 4: 10 },
    ],
    [
      "das Fenster",
      "Er öffnete das Fenster, um frische Luft hereinzulassen.",
      "window.jpeg",
      "/ˈfɛnʃtɐ/",
      { 11: 14, 15: 23 },
    ],
  ];

const newVocabSet = generateVocabSet({ vocabEntries });

Object.assign(commonNounsDE, newVocabSet);
