import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsEN: VocabSetRaw = [
  [
    "the airplane",
    "The airplane flew high above the clouds.",
    "commonNouns/airplane.jpeg",
    "/ˈeɪrˌpleɪn/",
    { 4: 12 },
  ],
  [
    "the baby",
    "The baby smiled at her mother.",
    "commonNouns/baby.jpeg",
    "/ˈbeɪbi/",
    { 4: 8 },
  ],
  [
    "the ball",
    "John kicked the ball towards the goal.",
    "commonNouns/ball.jpeg",
    "/bɔːl/",
    { 16: 20 },
  ],
  [
    "the beach",
    "We're planning to spend the day at the beach.",
    "commonNouns/beach.jpeg",
    "/biːtʃ/",
    { 39: 45 },
  ],
  [
    "the bed",
    "She lay down on her bed, exhausted from the day.",
    "commonNouns/bed.jpeg",
    "/bɛd/",
    { 20: 24 },
  ],
  [
    "the bicycle",
    "He rode the bicycle around the park.",
    "commonNouns/bicycle.jpeg",
    "/ˈbaɪsɪkl/",
    { 12: 19 },
  ],
  [
    "the bird",
    "The bird sang beautifully from its perch on the tree.",
    "commonNouns/bird.jpeg",
    "/bɝːd/",
    { 4: 8 },
  ],
  [
    "the boat",
    "They sailed down the river in the boat.",
    "commonNouns/boat.jpeg",
    "/boʊt/",
    { 34: 39 },
  ],
  [
    "the book",
    "She opened the book and started to read.",
    "commonNouns/book.jpeg",
    "/bʊk/",
    { 15: 19 },
  ],
  [
    "the bottle",
    "I filled the bottle with fresh spring water.",
    "commonNouns/bottle.jpeg",
    "/ˈbɒtl/",
    { 13: 19 },
  ],
  [
    "the bread",
    "She sliced the bread for breakfast.",
    "commonNouns/bread.jpeg",
    "/brɛd/",
    { 15: 20 },
  ],
  [
    "the camera",
    "He took a picture of the beautiful landscape with his camera.",
    "commonNouns/camera.jpeg",
    "/ˈkæmərə/",
    { 54: 61 },
  ],
  [
    "the car",
    "The car broke down on the way to the office.",
    "commonNouns/car.jpeg",
    "/kɑːr/",
    { 4: 7 },
  ],
  [
    "the cat",
    "The cat was sleeping on the sofa.",
    "commonNouns/cat.jpeg",
    "/kæt/",
    { 4: 7 },
  ],
  [
    "the chair",
    "He pulled out the chair and sat down.",
    "commonNouns/chair.jpeg",
    "/tʃeər/",
    { 18: 23 },
  ],
  ["the clock", "The clock struck midnight.", "clock.jpeg", "/klɒk/", { 4: 9 }],
  [
    "the clothes",
    "She folded the clothes and put them away.",
    "commonNouns/clothes.jpeg",
    "/kloʊðz/",
    { 15: 22 },
  ],
  [
    "the computer",
    "He turned on the computer to start his work.",
    "commonNouns/computer.jpeg",
    "/kəmˈpjuːtər/",
    { 17: 25 },
  ],
  [
    "the dog",
    "The dog was wagging its tail happily.",
    "commonNouns/dog.jpeg",
    "/dɔːg/",
    { 4: 7 },
  ],
  ["the door", "He knocked on the door.", "door.jpeg", "/dɔːr/", { 18: 23 }],
  [
    "the farm",
    "They spent the day working at the farm.",
    "commonNouns/farm.jpeg",
    "/fɑːrm/",
    { 34: 39 },
  ],
  [
    "the fish",
    "The fish swam swiftly in the clear water.",
    "commonNouns/fish.jpeg",
    "/fɪʃ/",
    { 4: 8 },
  ],
  [
    "the flower",
    "The flower bloomed beautifully in the garden.",
    "commonNouns/flower.jpeg",
    "/ˈflaʊər/",
    { 4: 10 },
  ],
  ["the food", "The food smelled delicious.", "food.jpeg", "/fuːd/", { 4: 8 }],
  [
    "the forest",
    "They went hiking in the forest.",
    "commonNouns/forest.jpeg",
    "/ˈfɔːrɪst/",
    { 24: 31 },
  ],
  [
    "the garden",
    "She was weeding in the garden.",
    "commonNouns/garden.jpeg",
    "/ˈɡɑːrdn/",
    { 23: 30 },
  ],
  [
    "the glass",
    "He filled his glass with juice.",
    "commonNouns/glass.jpeg",
    "/ɡlɑːs/",
    { 14: 19 },
  ],
  [
    "the grass",
    "The children were playing in the grass.",
    "commonNouns/grass.jpeg",
    "/ɡrɑːs/",
    { 33: 39 },
  ],
  [
    "the hand",
    "She held the baby's hand gently.",
    "commonNouns/hand.jpeg",
    "/hænd/",
    { 20: 24 },
  ],
  ["the house", "The house was quiet.", "house.jpeg", "/haʊs/", { 4: 9 }],
  ["the key", "He lost the key to his car.", "key.jpeg", "/kiː/", { 12: 15 }],
  [
    "the light",
    "There was light coming in from the window.",
    "commonNouns/light.jpeg",
    "/laɪt/",
    { 10: 15 },
  ],
  [
    "the money",
    "He saved all the money he could.",
    "commonNouns/money.jpeg",
    "/ˈmʌni/",
    { 17: 22 },
  ],
  [
    "the moon",
    "The moon was shining brightly in the night sky.",
    "commonNouns/moon.jpeg",
    "/muːn/",
    { 4: 8 },
  ],
  [
    "the mountain",
    "They climbed the mountain together.",
    "commonNouns/mountain.jpeg",
    "/ˈmaʊntɪn/",
    { 17: 25 },
  ],
  [
    "the paper",
    "He wrote a note on the paper.",
    "commonNouns/paper.jpeg",
    "/ˈpeɪpər/",
    { 23: 29 },
  ],
  [
    "the pencil",
    "She sharpened her pencil before starting her drawing.",
    "commonNouns/pencil.jpeg",
    "/ˈpɛnsəl/",
    { 18: 24 },
  ],
  [
    "the phone",
    "The phone rang in the middle of the night.",
    "commonNouns/phone.jpeg",
    "/foʊn/",
    { 4: 9 },
  ],
  [
    "the photograph",
    "The photograph brought back many memories.",
    "commonNouns/photograph.jpeg",
    "/ˈfoʊtəˌgræf/",
    { 4: 14 },
  ],
  [
    "the plate",
    "He washed the plate and put it back on the shelf.",
    "commonNouns/plate.jpeg",
    "/pleɪt/",
    { 14: 19 },
  ],
  [
    "the river",
    "They followed the river until they reached a small village.",
    "commonNouns/river.jpeg",
    "/ˈrɪvər/",
    { 18: 23 },
  ],
  [
    "the road",
    "The road was bumpy and full of potholes.",
    "commonNouns/road.jpeg",
    "/roʊd/",
    { 4: 8 },
  ],
  [
    "the shoe",
    "He tied the laces of his shoe.",
    "commonNouns/shoe.jpeg",
    "/ʃuː/",
    { 25: 30 },
  ],
  ["the sky", "The sky was full of clouds.", "sky.jpeg", "/skaɪ/", { 4: 7 }],
  [
    "the table",
    "She set the table for dinner.",
    "commonNouns/table.jpeg",
    "/ˈteɪbəl/",
    { 12: 17 },
  ],
  [
    "the train",
    "The train arrived at the station on time.",
    "commonNouns/train.jpeg",
    "/treɪn/",
    { 4: 9 },
  ],
  [
    "the tree",
    "The tree provided shade in the hot sun.",
    "commonNouns/tree.jpeg",
    "/triː/",
    { 4: 8 },
  ],
  [
    "the watch",
    "He looked at his watch and realized he was late.",
    "commonNouns/watch.jpeg",
    "/wɒtʃ/",
    { 17: 22 },
  ],
  [
    "the water",
    "She drank the water quickly.",
    "commonNouns/water.jpeg",
    "/ˈwɔːtər/",
    { 14: 19 },
  ],
  [
    "the window",
    "He opened the window to let in some fresh air.",
    "commonNouns/window.jpeg",
    "/ˈwɪndoʊ/",
    { 14: 20 },
  ],
];
