import { generateVocabSet } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";

export const commonNounsEN: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "the airplane",
      "The airplane flew high above the clouds.",
      "airplane.jpeg",
      "/ˈeɪrˌpleɪn/",
      { 4: 12 },
    ],
    [
      "the baby",
      "The baby smiled at her mother.",
      "baby.jpeg",
      "/ˈbeɪbi/",
      { 4: 8 },
    ],
    [
      "the ball",
      "John kicked the ball towards the goal.",
      "ball.jpeg",
      "/bɔːl/",
      { 16: 20 },
    ],
    [
      "the beach",
      "We're planning to spend the day at the beach.",
      "beach.jpeg",
      "/biːtʃ/",
      { 39: 45 },
    ],
    [
      "the bed",
      "She lay down on her bed, exhausted from the day.",
      "bed.jpeg",
      "/bɛd/",
      { 20: 24 },
    ],
    [
      "the bicycle",
      "He rode the bicycle around the park.",
      "bicycle.jpeg",
      "/ˈbaɪsɪkl/",
      { 12: 19 },
    ],
    [
      "the bird",
      "The bird sang beautifully from its perch on the tree.",
      "bird.jpeg",
      "/bɝːd/",
      { 4: 8 },
    ],
    [
      "the boat",
      "They sailed down the river in the boat.",
      "boat.jpeg",
      "/boʊt/",
      { 34: 39 },
    ],
    [
      "the book",
      "She opened the book and started to read.",
      "book.jpeg",
      "/bʊk/",
      { 15: 19 },
    ],
    [
      "the bottle",
      "I filled the bottle with fresh spring water.",
      "bottle.jpeg",
      "/ˈbɒtl/",
      { 13: 19 },
    ],
    [
      "the bread",
      "She sliced the bread for breakfast.",
      "bread.jpeg",
      "/brɛd/",
      { 15: 20 },
    ],
    [
      "the camera",
      "He took a picture of the beautiful landscape with his camera.",
      "camera.jpeg",
      "/ˈkæmərə/",
      { 54: 61 },
    ],
    [
      "the car",
      "The car broke down on the way to the office.",
      "car.jpeg",
      "/kɑːr/",
      { 4: 7 },
    ],
    [
      "the cat",
      "The cat was sleeping on the sofa.",
      "cat.jpeg",
      "/kæt/",
      { 4: 7 },
    ],
    [
      "the chair",
      "He pulled out the chair and sat down.",
      "chair.jpeg",
      "/tʃeər/",
      { 18: 23 },
    ],
    [
      "the clock",
      "The clock struck midnight.",
      "clock.jpeg",
      "/klɒk/",
      { 4: 9 },
    ],
    [
      "the clothes",
      "She folded the clothes and put them away.",
      "clothes.jpeg",
      "/kloʊðz/",
      { 15: 22 },
    ],
    [
      "the computer",
      "He turned on the computer to start his work.",
      "computer.jpeg",
      "/kəmˈpjuːtər/",
      { 17: 25 },
    ],
    [
      "the dog",
      "The dog was wagging its tail happily.",
      "dog.jpeg",
      "/dɔːg/",
      { 4: 7 },
    ],
    ["the door", "He knocked on the door.", "door.jpeg", "/dɔːr/", { 18: 23 }],
    [
      "the farm",
      "They spent the day working at the farm.",
      "farm.jpeg",
      "/fɑːrm/",
      { 34: 39 },
    ],
    [
      "the fish",
      "The fish swam swiftly in the clear water.",
      "fish.jpeg",
      "/fɪʃ/",
      { 4: 8 },
    ],
    [
      "the flower",
      "The flower bloomed beautifully in the garden.",
      "flower.jpeg",
      "/ˈflaʊər/",
      { 4: 10 },
    ],
    [
      "the food",
      "The food smelled delicious.",
      "food.jpeg",
      "/fuːd/",
      { 4: 8 },
    ],
    [
      "the forest",
      "They went hiking in the forest.",
      "forest.jpeg",
      "/ˈfɔːrɪst/",
      { 24: 31 },
    ],
    [
      "the garden",
      "She was weeding in the garden.",
      "garden.jpeg",
      "/ˈɡɑːrdn/",
      { 23: 30 },
    ],
    [
      "the glass",
      "He filled his glass with juice.",
      "glass.jpeg",
      "/ɡlɑːs/",
      { 14: 19 },
    ],
    [
      "the grass",
      "The children were playing in the grass.",
      "grass.jpeg",
      "/ɡrɑːs/",
      { 33: 39 },
    ],
    [
      "the hand",
      "She held the baby's hand gently.",
      "hand.jpeg",
      "/hænd/",
      { 20: 24 },
    ],
    ["the house", "The house was quiet.", "house.jpeg", "/haʊs/", { 4: 9 }],
    ["the key", "He lost the key to his car.", "key.jpeg", "/kiː/", { 12: 15 }],
    [
      "the light",
      "There was light coming in from the window.",
      "light.jpeg",
      "/laɪt/",
      { 10: 15 },
    ],
    [
      "the money",
      "He saved all the money he could.",
      "money.jpeg",
      "/ˈmʌni/",
      { 17: 22 },
    ],
    [
      "the moon",
      "The moon was shining brightly in the night sky.",
      "moon.jpeg",
      "/muːn/",
      { 4: 8 },
    ],
    [
      "the mountain",
      "They climbed the mountain together.",
      "mountain.jpeg",
      "/ˈmaʊntɪn/",
      { 17: 25 },
    ],
    [
      "the paper",
      "He wrote a note on the paper.",
      "paper.jpeg",
      "/ˈpeɪpər/",
      { 23: 29 },
    ],
    [
      "the pencil",
      "She sharpened her pencil before starting her drawing.",
      "pencil.jpeg",
      "/ˈpɛnsəl/",
      { 18: 24 },
    ],
    [
      "the phone",
      "The phone rang in the middle of the night.",
      "phone.jpeg",
      "/foʊn/",
      { 4: 9 },
    ],
    [
      "the photograph",
      "The photograph brought back many memories.",
      "photograph.jpeg",
      "/ˈfoʊtəˌgræf/",
      { 4: 14 },
    ],
    [
      "the plate",
      "He washed the plate and put it back on the shelf.",
      "plate.jpeg",
      "/pleɪt/",
      { 14: 19 },
    ],
    [
      "the river",
      "They followed the river until they reached a small village.",
      "river.jpeg",
      "/ˈrɪvər/",
      { 18: 23 },
    ],
    [
      "the road",
      "The road was bumpy and full of potholes.",
      "road.jpeg",
      "/roʊd/",
      { 4: 8 },
    ],
    [
      "the shoe",
      "He tied the laces of his shoe.",
      "shoe.jpeg",
      "/ʃuː/",
      { 25: 30 },
    ],
    ["the sky", "The sky was full of clouds.", "sky.jpeg", "/skaɪ/", { 4: 7 }],
    [
      "the table",
      "She set the table for dinner.",
      "table.jpeg",
      "/ˈteɪbəl/",
      { 12: 17 },
    ],
    [
      "the train",
      "The train arrived at the station on time.",
      "train.jpeg",
      "/treɪn/",
      { 4: 9 },
    ],
    [
      "the tree",
      "The tree provided shade in the hot sun.",
      "tree.jpeg",
      "/triː/",
      { 4: 8 },
    ],
    [
      "the watch",
      "He looked at his watch and realized he was late.",
      "watch.jpeg",
      "/wɒtʃ/",
      { 17: 22 },
    ],
    [
      "the water",
      "She drank the water quickly.",
      "water.jpeg",
      "/ˈwɔːtər/",
      { 14: 19 },
    ],
    [
      "the window",
      "He opened the window to let in some fresh air.",
      "window.jpeg",
      "/ˈwɪndoʊ/",
      { 14: 20 },
    ],
  ];

const newVocabSet = generateVocabSet({ vocabEntries });

Object.assign(commonNounsEN, newVocabSet);
