import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsES: VocabSetRaw = [
  [
    "el avión",
    "El avión voló alto por encima de las nubes.",
    "commonNouns/airplane.jpeg",
    "/aˈbjon/",
    { 0: 2, 3: 8 },
  ],
  [
    "el bebé",
    "El bebé sonrió a su madre.",
    "commonNouns/baby.jpeg",
    "/beˈbe/",
    { 0: 2, 3: 7 },
  ],
  [
    "la pelota",
    "John pateó la pelota hacia la meta.",
    "commonNouns/ball.jpeg",
    "/peˈlota/",
    { 11: 13, 14: 20 },
  ],
  [
    "la playa",
    "Planeamos pasar el día en la playa.",
    "commonNouns/beach.jpeg",
    "/ˈplaʝa/",
    { 26: 28, 29: 35 },
  ],
  [
    "la cama",
    "Se tumbó en la cama, agotada del día.",
    "commonNouns/bed.jpeg",
    "/ˈkama/",
    { 12: 14, 15: 20 },
  ],
  [
    "la bicicleta",
    "Rodó la bicicleta por el parque.",
    "commonNouns/bicycle.jpeg",
    "/biθiˈkleta/",
    { 5: 7, 8: 17 },
  ],
  [
    "el pájaro",
    "El pájaro cantaba hermosamente desde su posadero en el árbol.",
    "commonNouns/bird.jpeg",
    "/ˈpaʝaro/",
    { 0: 2, 3: 9 },
  ],
  [
    "la barca",
    "Navegaron por el río en la barca.",
    "commonNouns/boat.jpeg",
    "/ˈbarka/",
    { 24: 26, 27: 33 },
  ],
  [
    "el libro",
    "Ella abrió el libro y comenzó a leer.",
    "commonNouns/book.jpeg",
    "/li'bɾo/",
    { 11: 13, 14: 19 },
  ],
  [
    "la botella",
    "Llené la botella con agua fresca de manantial.",
    "commonNouns/bottle.jpeg",
    "/bo'teʎa/",
    { 6: 8, 9: 16 },
  ],
  [
    "el pan",
    "Ella cortó el pan para el desayuno.",
    "commonNouns/bread.jpeg",
    "/pan/",
    { 11: 13, 14: 17 },
  ],
  [
    "la cámara",
    "Tomó una foto del hermoso paisaje con su cámara.",
    "commonNouns/camera.jpeg",
    "/'kamara/",
    { 41: 48 },
  ],
  [
    "el coche",
    "El coche se averió en el camino a la oficina.",
    "commonNouns/car.jpeg",
    "/'kotʃe/",
    { 0: 2, 3: 8 },
  ],
  [
    "el gato",
    "El gato estaba durmiendo en el sofá.",
    "commonNouns/cat.jpeg",
    "/'gato/",
    { 0: 2, 3: 7 },
  ],
  [
    "la silla",
    "Sacó la silla y se sentó.",
    "commonNouns/chair.jpeg",
    "/'siʎa/",
    { 5: 7, 8: 13 },
  ],
  [
    "el reloj",
    "El reloj marcó la medianoche.",
    "commonNouns/clock.jpeg",
    "/re'lox/",
    { 0: 2, 3: 8 },
  ],
  [
    "la ropa",
    "Dobló la ropa y la guardó.",
    "commonNouns/clothes.jpeg",
    "/'ropa/",
    { 6: 8, 9: 13 },
  ],
  [
    "la computadora",
    "Encendió la computadora para comenzar su trabajo.",
    "commonNouns/computer.jpeg",
    "/kompu'tadoɾa/",
    { 9: 11, 12: 23 },
  ],
  [
    "el perro",
    "El perro movía su cola felizmente.",
    "commonNouns/dog.jpeg",
    "/'pero/",
    { 0: 2, 3: 8 },
  ],
  [
    "la puerta",
    "Golpeó la puerta.",
    "commonNouns/door.jpeg",
    "/'pwerta/",
    { 7: 9, 10: 17 },
  ],
  [
    "la granja",
    "Pasaron el día trabajando en la granja.",
    "commonNouns/farm.jpeg",
    "/'granxa/",
    { 29: 31, 32: 39 },
  ],
  [
    "el pez",
    "El pez nadó rápidamente en el agua clara.",
    "commonNouns/fish.jpeg",
    "/peθ/",
    { 0: 2, 3: 6 },
  ],
  [
    "la flor",
    "La flor floreció hermosamente en el jardín.",
    "commonNouns/flower.jpeg",
    "/floɾ/",
    { 0: 2, 3: 7 },
  ],
  [
    "la comida",
    "La comida olía delicioso.",
    "commonNouns/food.jpeg",
    "/ko'mida/",
    { 0: 2, 3: 9 },
  ],
  [
    "el bosque",
    "Fueron a caminar al bosque.",
    "commonNouns/forest.jpeg",
    "/'boske/",
    { 20: 27 },
  ],
  [
    "el jardín",
    "Estaba deshierbando en el jardín.",
    "commonNouns/garden.jpeg",
    "/xar'din/",
    { 23: 25, 26: 33 },
  ],
  [
    "el vaso",
    "Llenó su vaso con jugo.",
    "commonNouns/glass.jpeg",
    "/'baso/",
    { 9: 13 },
  ],
  [
    "la hierba",
    "Los niños estaban jugando en la hierba.",
    "commonNouns/grass.jpeg",
    "/'ʝeɾβa/",
    { 29: 31, 32: 39 },
  ],
  [
    "la mano",
    "Sostenía la mano del bebé suavemente.",
    "commonNouns/hand.jpeg",
    "/'mano/",
    { 9: 11, 12: 16 },
  ],
  [
    "la casa",
    "La casa estaba en silencio.",
    "commonNouns/house.jpeg",
    "/'kasa/",
    { 0: 2, 3: 7 },
  ],
  [
    "la llave",
    "Perdió la llave de su coche.",
    "commonNouns/key.jpeg",
    "/'ʝaβe/",
    { 7: 9, 10: 15 },
  ],
  [
    "la luz",
    "Había luz entrando por la ventana.",
    "commonNouns/light.jpeg",
    "/lus/",
    { 6: 9 },
  ],
  [
    "el dinero",
    "Guardó todo el dinero que pudo.",
    "commonNouns/money.jpeg",
    "/di'neɾo/",
    { 12: 14, 15: 21 },
  ],
  [
    "la luna",
    "La luna brillaba intensamente en el cielo nocturno.",
    "commonNouns/moon.jpeg",
    "/'luna/",
    { 0: 2, 3: 7 },
  ],
  [
    "la montaña",
    "Escalaron la montaña juntos.",
    "commonNouns/mountain.jpeg",
    "/mon'taɲa/",
    { 10: 12, 13: 20 },
  ],
  [
    "el papel",
    "Escribió una nota en el papel.",
    "commonNouns/paper.jpeg",
    "/pa'pel/",
    { 21: 23, 24: 30 },
  ],
  [
    "el lápiz",
    "Afiló su lápiz antes de comenzar su dibujo.",
    "commonNouns/pencil.jpeg",
    "/'la.piθ/",
    { 9: 14 },
  ],
  [
    "el teléfono",
    "El teléfono sonó en medio de la noche.",
    "commonNouns/phone.jpeg",
    "/te'lefono/",
    { 0: 2, 3: 11 },
  ],
  [
    "la fotografía",
    "La fotografía trajo muchos recuerdos.",
    "commonNouns/photograph.jpeg",
    "/foto'grafia/",
    { 0: 2, 3: 13 },
  ],
  [
    "el plato",
    "Lavó el plato y lo puso de nuevo en el estante.",
    "commonNouns/plate.jpeg",
    "/'plato/",
    { 5: 7, 8: 13 },
  ],
  [
    "el río",
    "Siguieron el río hasta llegar a un pequeño pueblo.",
    "commonNouns/river.jpeg",
    "/'rio/",
    { 10: 12, 13: 16 },
  ],
  [
    "la carretera",
    "La carretera estaba llena de baches y hoyos.",
    "commonNouns/road.jpeg",
    "/karre'tera/",
    { 0: 2, 3: 12 },
  ],
  [
    "el zapato",
    "Ató los cordones de su zapato.",
    "commonNouns/shoe.jpeg",
    "/θa'pato/",
    { 23: 30 },
  ],
  [
    "el cielo",
    "El cielo estaba lleno de nubes.",
    "commonNouns/sky.jpeg",
    "/'θjelo/",
    { 0: 2, 3: 8 },
  ],
  [
    "la mesa",
    "Puso la mesa para la cena.",
    "commonNouns/table.jpeg",
    "/'mesa/",
    { 5: 7, 8: 12 },
  ],
  [
    "el tren",
    "El tren llegó a la estación a tiempo.",
    "commonNouns/train.jpeg",
    "/tɾen/",
    { 0: 2, 3: 7 },
  ],
  [
    "el árbol",
    "El árbol proporcionaba sombra en el sol caliente.",
    "commonNouns/tree.jpeg",
    "/'arbol/",
    { 0: 2, 3: 8 },
  ],
  [
    "el reloj (de pulsera)",
    "Miró su reloj de pulsera y se dio cuenta de que llegaba tarde.",
    "commonNouns/watch.jpeg",
    "/re'lox/",
    { 8: 13, 14: 16, 17: 24 },
  ],
  [
    "el agua",
    "Bebió el agua rápidamente.",
    "commonNouns/water.jpeg",
    "/'aɣwa/",
    { 6: 8, 9: 13 },
  ],
  [
    "la ventana",
    "Abrió la ventana para dejar entrar un poco de aire fresco.",
    "commonNouns/window.jpeg",
    "/βen'tana/",
    { 6: 8, 9: 16 },
  ],
];
