import { generateVocabSet } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";

export const commonNounsFR: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "l'avion",
      "L'avion volait haut au-dessus des nuages.",
      "airplane.jpeg",
      "/avjɔ̃/",
      { 0: 7 },
    ],
    [
      "le bébé",
      "Le bébé a souri à sa mère.",
      "baby.jpeg",
      "/bebe/",
      { 0: 2, 3: 7 },
    ],
    [
      "le ballon",
      "John a frappé le ballon vers le but.",
      "ball.jpeg",
      "/balɔ̃/",
      { 14: 16, 17: 23 },
    ],
    [
      "la plage",
      "Nous prévoyons de passer la journée à la plage.",
      "beach.jpeg",
      "/plaʒ/",
      { 38: 40, 41: 47 },
    ],
    [
      "le lit",
      "Elle s'est allongée sur son lit, épuisée par la journée.",
      "bed.jpeg",
      "/li/",
      { 28: 32 },
    ],
    [
      "le vélo",
      "Il a fait le tour du parc en vélo.",
      "bicycle.jpeg",
      "/velo/",
      { 29: 34 },
    ],
    [
      "l'oiseau",
      "L'oiseau chantait magnifiquement depuis sa perche dans l'arbre.",
      "bird.jpeg",
      "/wazo/",
      { 0: 8 },
    ],
    [
      "le bateau",
      "Ils ont navigué sur la rivière en bateau.",
      "boat.jpeg",
      "/bato/",
      { 34: 41 },
    ],
    [
      "le livre",
      "Elle a ouvert le livre et a commencé à lire.",
      "book.jpeg",
      "/livʁ/",
      { 14: 16, 17: 22 },
    ],
    [
      "la bouteille",
      "J'ai rempli la bouteille avec de l'eau de source fraîche.",
      "bottle.jpeg",
      "/butɛj/",
      { 12: 14, 15: 24 },
    ],
    [
      "le pain",
      "Elle a tranché le pain pour le petit déjeuner.",
      "bread.jpeg",
      "/pɛ̃/",
      { 15: 17, 18: 22 },
    ],
    [
      "l'appareil photo",
      "Il a pris une photo du magnifique paysage avec son appareil photo.",
      "camera.jpeg",
      "/apaʁɛj foto/",
      { 51: 59, 60: 66 },
    ],
    [
      "la voiture",
      "La voiture est tombée en panne en route pour le bureau.",
      "car.jpeg",
      "/vwatyʁ/",
      { 0: 2, 3: 10 },
    ],
    [
      "le chat",
      "Le chat dormait sur le canapé.",
      "cat.jpeg",
      "/ʃa/",
      { 0: 2, 3: 7 },
    ],
    [
      "la chaise",
      "Il a tiré la chaise et s'est assis.",
      "chair.jpeg",
      "/ʃɛz/",
      { 10: 12, 13: 19 },
    ],
    [
      "l'horloge",
      "L'horloge a sonné minuit.",
      "clock.jpeg",
      "/ɔʁlɔʒ/",
      { 0: 9 },
    ],
    [
      "les vêtements",
      "Elle a plié les vêtements et les a rangés.",
      "clothes.jpeg",
      "/vɛtmɑ̃/",
      { 12: 15, 16: 25 },
    ],
    [
      "l'ordinateur",
      "Il a allumé l'ordinateur pour commencer son travail.",
      "computer.jpeg",
      "/ɔʁdinatœʁ/",
      { 12: 24 },
    ],
    [
      "le chien",
      "Le chien remuait joyeusement la queue.",
      "dog.jpeg",
      "/ʃjɛ̃/",
      { 0: 2, 3: 8 },
    ],
    [
      "la porte",
      "Il a frappé à la porte.",
      "door.jpeg",
      "/pɔʁt/",
      { 14: 16, 17: 23 },
    ],
    [
      "la ferme",
      "Ils ont passé la journée à travailler à la ferme.",
      "farm.jpeg",
      "/fɛʁm/",
      { 40: 42, 43: 49 },
    ],
    [
      "le poisson",
      "Le poisson nageait rapidement dans l'eau claire.",
      "fish.jpeg",
      "/pwasɔ̃/",
      { 0: 2, 3: 10 },
    ],
    [
      "la fleur",
      "La fleur a magnifiquement fleuri dans le jardin.",
      "flower.jpeg",
      "/flœʁ/",
      { 0: 2, 3: 8 },
    ],
    [
      "la nourriture",
      "La nourriture sentait délicieux.",
      "food.jpeg",
      "/nuʁityʁ/",
      { 0: 2, 3: 13 },
    ],
    [
      "la forêt",
      "Ils sont allés faire de la randonnée dans la forêt.",
      "forest.jpeg",
      "/fɔʁɛ/",
      { 42: 44, 45: 51 },
    ],
    [
      "le jardin",
      "Elle désherbait dans le jardin.",
      "garden.jpeg",
      "/ʒaʁdɛ̃/",
      { 21: 23, 24: 31 },
    ],
    [
      "le verre",
      "Il a rempli son verre de jus.",
      "glass.jpeg",
      "/vɛʁ/",
      { 16: 21 },
    ],
    [
      "l'herbe",
      "Les enfants jouaient dans l'herbe.",
      "grass.jpeg",
      "/ɛʁb/",
      { 26: 34 },
    ],
    [
      "la main",
      "Elle tenait doucement la main du bébé.",
      "hand.jpeg",
      "/mɛ̃/",
      { 22: 24, 25: 29 },
    ],
    [
      "la maison",
      "La maison était calme.",
      "house.jpeg",
      "/me.zɔ̃/",
      { 0: 2, 3: 9 },
    ],
    [
      "la clé",
      "Il a perdu la clé de sa voiture.",
      "key.jpeg",
      "/kle/",
      { 11: 13, 14: 17 },
    ],
    [
      "la lumière",
      "Il y avait de la lumière qui venait de la fenêtre.",
      "light.jpeg",
      "/lymjɛʁ/",
      { 14: 16, 17: 24 },
    ],
    [
      "l'argent",
      "Il a économisé tout l'argent qu'il pouvait.",
      "money.jpeg",
      "/aʁʒɑ̃/",
      { 20: 28 },
    ],
    [
      "la lune",
      "La lune brillait vivement dans le ciel nocturne.",
      "moon.jpeg",
      "/lyn/",
      { 0: 2, 3: 7 },
    ],
    [
      "la montagne",
      "Ils ont grimpé la montagne ensemble.",
      "mountain.jpeg",
      "/mɔ̃taɲ/",
      { 15: 17, 18: 26 },
    ],
    [
      "le papier",
      "Il a écrit une note sur le papier.",
      "paper.jpeg",
      "/papje/",
      { 24: 26, 27: 34 },
    ],
    [
      "le crayon",
      "Elle a aiguisé son crayon avant de commencer son dessin.",
      "pencil.jpeg",
      "/kʁɛjɔ̃/",
      { 19: 25 },
    ],
    [
      "le téléphone",
      "Le téléphone a sonné au milieu de la nuit.",
      "phone.jpeg",
      "/telefɔn/",
      { 0: 2, 3: 12 },
    ],
    [
      "la photographie",
      "La photographie a ravivé de nombreux souvenirs.",
      "photograph.jpeg",
      "/fɔtɔgʁafi/",
      { 0: 2, 3: 15 },
    ],
    [
      "l'assiette",
      "Il a lavé l'assiette et l'a remise sur l'étagère.",
      "plate.jpeg",
      "/asjɛt/",
      { 10: 20 },
    ],
    [
      "la rivière",
      "Ils ont suivi la rivière jusqu'à atteindre un petit village.",
      "river.jpeg",
      "/ʁivjɛʁ/",
      { 14: 16, 17: 24 },
    ],
    [
      "la route",
      "La route était cahoteuse et pleine de nids de poule.",
      "road.jpeg",
      "/ʁut/",
      { 0: 2, 3: 8 },
    ],
    [
      "la chaussure",
      "Il a attaché les lacets de sa chaussure.",
      "shoe.jpeg",
      "/ʃosyʁ/",
      { 30: 40 },
    ],
    [
      "le ciel",
      "Le ciel était plein de nuages.",
      "sky.jpeg",
      "/sjɛl/",
      { 0: 2, 3: 7 },
    ],
    [
      "la table",
      "Elle a dressé la table pour le dîner.",
      "table.jpeg",
      "/tabl/",
      { 14: 16, 17: 22 },
    ],
    [
      "le train",
      "Le train est arrivé à la gare à l'heure.",
      "train.jpeg",
      "/tʁɛ̃/",
      { 0: 2, 3: 8 },
    ],
    [
      "l'arbre",
      "L'arbre fournissait de l'ombre sous le soleil brûlant.",
      "tree.jpeg",
      "/aʁbʁ/",
      { 0: 7 },
    ],
    [
      "la montre",
      "Il a regardé sa montre et a réalisé qu'il était en retard.",
      "watch.jpeg",
      "/mɔ̃tʁ/",
      { 16: 22 },
    ],
    ["l'eau", "Elle a rapidement bu l'eau.", "water.jpeg", "/o/", { 21: 27 }],
    [
      "la fenêtre",
      "Il a ouvert la fenêtre pour laisser entrer de l'air frais.",
      "window.jpeg",
      "/fənɛtʁ/",
      { 12: 14, 15: 22 },
    ],
  ];

const newVocabSet = generateVocabSet({ vocabEntries });

Object.assign(commonNounsFR, newVocabSet);
