import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsFR: VocabSetRaw = [
  [
    "l'avion",
    "L'avion volait haut au-dessus des nuages.",
    "commonNouns/airplane.jpeg",
    "/avjɔ̃/",
    { 0: 7 },
  ],
  [
    "le bébé",
    "Le bébé a souri à sa mère.",
    "commonNouns/baby.jpeg",
    "/bebe/",
    { 0: 2, 3: 7 },
  ],
  [
    "le ballon",
    "John a frappé le ballon vers le but.",
    "commonNouns/ball.jpeg",
    "/balɔ̃/",
    { 14: 16, 17: 23 },
  ],
  [
    "la plage",
    "Nous prévoyons de passer la journée à la plage.",
    "commonNouns/beach.jpeg",
    "/plaʒ/",
    { 38: 40, 41: 47 },
  ],
  [
    "le lit",
    "Elle s'est allongée sur son lit, épuisée par la journée.",
    "commonNouns/bed.jpeg",
    "/li/",
    { 28: 32 },
  ],
  [
    "le vélo",
    "Il a fait le tour du parc en vélo.",
    "commonNouns/bicycle.jpeg",
    "/velo/",
    { 29: 34 },
  ],
  [
    "l'oiseau",
    "L'oiseau chantait magnifiquement depuis sa perche dans l'arbre.",
    "commonNouns/bird.jpeg",
    "/wazo/",
    { 0: 8 },
  ],
  [
    "le bateau",
    "Ils ont navigué sur la rivière en bateau.",
    "commonNouns/boat.jpeg",
    "/bato/",
    { 34: 41 },
  ],
  [
    "le livre",
    "Elle a ouvert le livre et a commencé à lire.",
    "commonNouns/book.jpeg",
    "/livʁ/",
    { 14: 16, 17: 22 },
  ],
  [
    "la bouteille",
    "J'ai rempli la bouteille avec de l'eau de source fraîche.",
    "commonNouns/bottle.jpeg",
    "/butɛj/",
    { 12: 14, 15: 24 },
  ],
  [
    "le pain",
    "Elle a tranché le pain pour le petit déjeuner.",
    "commonNouns/bread.jpeg",
    "/pɛ̃/",
    { 15: 17, 18: 22 },
  ],
  [
    "l'appareil photo",
    "Il a pris une photo du magnifique paysage avec son appareil photo.",
    "commonNouns/camera.jpeg",
    "/apaʁɛj foto/",
    { 51: 59, 60: 66 },
  ],
  [
    "la voiture",
    "La voiture est tombée en panne en route pour le bureau.",
    "commonNouns/car.jpeg",
    "/vwatyʁ/",
    { 0: 2, 3: 10 },
  ],
  [
    "le chat",
    "Le chat dormait sur le canapé.",
    "commonNouns/cat.jpeg",
    "/ʃa/",
    { 0: 2, 3: 7 },
  ],
  [
    "la chaise",
    "Il a tiré la chaise et s'est assis.",
    "commonNouns/chair.jpeg",
    "/ʃɛz/",
    { 10: 12, 13: 19 },
  ],
  [
    "l'horloge",
    "L'horloge a sonné minuit.",
    "commonNouns/clock.jpeg",
    "/ɔʁlɔʒ/",
    { 0: 9 },
  ],
  [
    "les vêtements",
    "Elle a plié les vêtements et les a rangés.",
    "commonNouns/clothes.jpeg",
    "/vɛtmɑ̃/",
    { 12: 15, 16: 25 },
  ],
  [
    "l'ordinateur",
    "Il a allumé l'ordinateur pour commencer son travail.",
    "commonNouns/computer.jpeg",
    "/ɔʁdinatœʁ/",
    { 12: 24 },
  ],
  [
    "le chien",
    "Le chien remuait joyeusement la queue.",
    "commonNouns/dog.jpeg",
    "/ʃjɛ̃/",
    { 0: 2, 3: 8 },
  ],
  [
    "la porte",
    "Il a frappé à la porte.",
    "commonNouns/door.jpeg",
    "/pɔʁt/",
    { 14: 16, 17: 23 },
  ],
  [
    "la ferme",
    "Ils ont passé la journée à travailler à la ferme.",
    "commonNouns/farm.jpeg",
    "/fɛʁm/",
    { 40: 42, 43: 49 },
  ],
  [
    "le poisson",
    "Le poisson nageait rapidement dans l'eau claire.",
    "commonNouns/fish.jpeg",
    "/pwasɔ̃/",
    { 0: 2, 3: 10 },
  ],
  [
    "la fleur",
    "La fleur a magnifiquement fleuri dans le jardin.",
    "commonNouns/flower.jpeg",
    "/flœʁ/",
    { 0: 2, 3: 8 },
  ],
  [
    "la nourriture",
    "La nourriture sentait délicieux.",
    "commonNouns/food.jpeg",
    "/nuʁityʁ/",
    { 0: 2, 3: 13 },
  ],
  [
    "la forêt",
    "Ils sont allés faire de la randonnée dans la forêt.",
    "commonNouns/forest.jpeg",
    "/fɔʁɛ/",
    { 42: 44, 45: 51 },
  ],
  [
    "le jardin",
    "Elle désherbait dans le jardin.",
    "commonNouns/garden.jpeg",
    "/ʒaʁdɛ̃/",
    { 21: 23, 24: 31 },
  ],
  [
    "le verre",
    "Il a rempli son verre de jus.",
    "commonNouns/glass.jpeg",
    "/vɛʁ/",
    { 16: 21 },
  ],
  [
    "l'herbe",
    "Les enfants jouaient dans l'herbe.",
    "commonNouns/grass.jpeg",
    "/ɛʁb/",
    { 26: 34 },
  ],
  [
    "la main",
    "Elle tenait doucement la main du bébé.",
    "commonNouns/hand.jpeg",
    "/mɛ̃/",
    { 22: 24, 25: 29 },
  ],
  [
    "la maison",
    "La maison était calme.",
    "commonNouns/house.jpeg",
    "/me.zɔ̃/",
    { 0: 2, 3: 9 },
  ],
  [
    "la clé",
    "Il a perdu la clé de sa voiture.",
    "commonNouns/key.jpeg",
    "/kle/",
    { 11: 13, 14: 17 },
  ],
  [
    "la lumière",
    "Il y avait de la lumière qui venait de la fenêtre.",
    "commonNouns/light.jpeg",
    "/lymjɛʁ/",
    { 14: 16, 17: 24 },
  ],
  [
    "l'argent",
    "Il a économisé tout l'argent qu'il pouvait.",
    "commonNouns/money.jpeg",
    "/aʁʒɑ̃/",
    { 20: 28 },
  ],
  [
    "la lune",
    "La lune brillait vivement dans le ciel nocturne.",
    "commonNouns/moon.jpeg",
    "/lyn/",
    { 0: 2, 3: 7 },
  ],
  [
    "la montagne",
    "Ils ont grimpé la montagne ensemble.",
    "commonNouns/mountain.jpeg",
    "/mɔ̃taɲ/",
    { 15: 17, 18: 26 },
  ],
  [
    "le papier",
    "Il a écrit une note sur le papier.",
    "commonNouns/paper.jpeg",
    "/papje/",
    { 24: 26, 27: 34 },
  ],
  [
    "le crayon",
    "Elle a aiguisé son crayon avant de commencer son dessin.",
    "commonNouns/pencil.jpeg",
    "/kʁɛjɔ̃/",
    { 19: 25 },
  ],
  [
    "le téléphone",
    "Le téléphone a sonné au milieu de la nuit.",
    "commonNouns/phone.jpeg",
    "/telefɔn/",
    { 0: 2, 3: 12 },
  ],
  [
    "la photographie",
    "La photographie a ravivé de nombreux souvenirs.",
    "commonNouns/photograph.jpeg",
    "/fɔtɔgʁafi/",
    { 0: 2, 3: 15 },
  ],
  [
    "l'assiette",
    "Il a lavé l'assiette et l'a remise sur l'étagère.",
    "commonNouns/plate.jpeg",
    "/asjɛt/",
    { 10: 20 },
  ],
  [
    "la rivière",
    "Ils ont suivi la rivière jusqu'à atteindre un petit village.",
    "commonNouns/river.jpeg",
    "/ʁivjɛʁ/",
    { 14: 16, 17: 24 },
  ],
  [
    "la route",
    "La route était cahoteuse et pleine de nids de poule.",
    "commonNouns/road.jpeg",
    "/ʁut/",
    { 0: 2, 3: 8 },
  ],
  [
    "la chaussure",
    "Il a attaché les lacets de sa chaussure.",
    "commonNouns/shoe.jpeg",
    "/ʃosyʁ/",
    { 30: 40 },
  ],
  [
    "le ciel",
    "Le ciel était plein de nuages.",
    "commonNouns/sky.jpeg",
    "/sjɛl/",
    { 0: 2, 3: 7 },
  ],
  [
    "la table",
    "Elle a dressé la table pour le dîner.",
    "commonNouns/table.jpeg",
    "/tabl/",
    { 14: 16, 17: 22 },
  ],
  [
    "le train",
    "Le train est arrivé à la gare à l'heure.",
    "commonNouns/train.jpeg",
    "/tʁɛ̃/",
    { 0: 2, 3: 8 },
  ],
  [
    "l'arbre",
    "L'arbre fournissait de l'ombre sous le soleil brûlant.",
    "commonNouns/tree.jpeg",
    "/aʁbʁ/",
    { 0: 7 },
  ],
  [
    "la montre",
    "Il a regardé sa montre et a réalisé qu'il était en retard.",
    "commonNouns/watch.jpeg",
    "/mɔ̃tʁ/",
    { 16: 22 },
  ],
  [
    "l'eau",
    "Elle a rapidement bu l'eau.",
    "commonNouns/water.jpeg",
    "/o/",
    { 21: 27 },
  ],
  [
    "la fenêtre",
    "Il a ouvert la fenêtre pour laisser entrer de l'air frais.",
    "commonNouns/window.jpeg",
    "/fənɛtʁ/",
    { 12: 14, 15: 22 },
  ],
];
