import { generateVocabSet } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";

export const commonNounsIT: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "l'aereo",
      "L'aereo volava alto sopra le nuvole.",
      "airplane.jpeg",
      "/aˈɛːreo/",
      { 0: 7 },
    ],
    [
      "il bambino",
      "Il bambino ha sorriso a sua madre.",
      "baby.jpeg",
      "/bamˈbiːno/",
      { 0: 2, 3: 10 },
    ],
    [
      "la palla",
      "Giovanni ha calciato la palla verso la porta.",
      "ball.jpeg",
      "/ˈpalla/",
      { 21: 23, 24: 29 },
    ],
    [
      "la spiaggia",
      "Stiamo pianificando di passare la giornata in spiaggia.",
      "beach.jpeg",
      "/ˈspjaddʒa/",
      { 46: 55 },
    ],
    [
      "il letto",
      "Si sdraiò sul suo letto, esausta dalla giornata.",
      "bed.jpeg",
      "/ˈletto/",
      { 18: 24 },
    ],
    [
      "la bicicletta",
      "Ha girato attorno al parco con la bicicletta.",
      "bicycle.jpeg",
      "/bitʃiˈkletta/",
      { 31: 33, 34: 45 },
    ],
    [
      "l'uccello",
      "L'uccello cantava splendidamente dal suo posatoio sull'albero.",
      "bird.jpeg",
      "/utˈtʃɛllo/",
      { 0: 9 },
    ],
    [
      "la barca",
      "Hanno navigato sul fiume con la barca.",
      "boat.jpeg",
      "/ˈbarka/",
      { 29: 31, 32: 38 },
    ],
    [
      "il libro",
      "Ha aperto il libro e ha cominciato a leggere.",
      "book.jpeg",
      "/ˈlibro/",
      { 10: 12, 13: 18 },
    ],
    [
      "la bottiglia",
      "Ho riempito la bottiglia con acqua di sorgente fresca.",
      "bottle.jpeg",
      "/botˈtiʎʎa/",
      { 12: 14, 15: 24 },
    ],
    [
      "il pane",
      "Ha tagliato il pane per la colazione.",
      "bread.jpeg",
      "/ˈpane/",
      { 12: 14, 15: 19 },
    ],
    [
      "la macchina fotografica",
      "Ha scattato una foto del bellissimo paesaggio con la sua macchina fotografica.",
      "camera.jpeg",
      "/ˌmak'kina fotoˈɡraːfika/",
      { 50: 52, 57: 65, 66: 78 },
    ],
    [
      "la macchina",
      "La macchina si è rotta lungo il percorso per l'ufficio.",
      "car.jpeg",
      "/makˈkina/",
      { 0: 2, 3: 11 },
    ],
    [
      "il gatto",
      "Il gatto dormiva sul divano.",
      "cat.jpeg",
      "/ˈɡatto/",
      { 0: 2, 3: 8 },
    ],
    [
      "la sedia",
      "Ha tirato fuori la sedia e si è seduto.",
      "chair.jpeg",
      "/ˈsɛdja/",
      { 16: 18, 19: 24 },
    ],
    [
      "l'orologio",
      "L'orologio segnava la mezzanotte.",
      "clock.jpeg",
      "/oroloˈdʒo/",
      { 0: 10 },
    ],
    [
      "i vestiti",
      "Ha piegato i vestiti e li ha messi via.",
      "clothes.jpeg",
      "/veˈstiti/",
      { 11: 12, 13: 20 },
    ],
    [
      "il computer",
      "Ha acceso il computer per iniziare il suo lavoro.",
      "computer.jpeg",
      "/komˈpjuter/",
      { 10: 12, 13: 21 },
    ],
    [
      "il cane",
      "Il cane scodinzolava felicemente.",
      "dog.jpeg",
      "/ˈkane/",
      { 0: 2, 3: 7 },
    ],
    ["la porta", "Ha bussato alla porta.", "door.jpeg", "/ˈporta/", { 16: 22 }],
    [
      "la fattoria",
      "Hanno trascorso la giornata lavorando alla fattoria.",
      "farm.jpeg",
      "/fattoˈria/",
      { 43: 52 },
    ],
    [
      "il pesce",
      "Il pesce nuotava velocemente nell'acqua chiara.",
      "fish.jpeg",
      "/ˈpeʃʃe/",
      { 0: 2, 3: 8 },
    ],
    [
      "il fiore",
      "Il fiore sbocciava splendidamente nel giardino.",
      "flower.jpeg",
      "/ˈfjore/",
      { 0: 2, 3: 8 },
    ],
    [
      "il cibo",
      "Il cibo aveva un profumo delizioso.",
      "food.jpeg",
      "/ˈtʃibo/",
      { 0: 2, 3: 7 },
    ],
    [
      "la foresta",
      "Sono andati a fare un'escursione nella foresta.",
      "forest.jpeg",
      "/forˈesta/",
      { 39: 47 },
    ],
    [
      "il giardino",
      "Stava sarchiando nel giardino.",
      "garden.jpeg",
      "/dʒarˈdino/",
      { 21: 30 },
    ],
    [
      "il bicchiere",
      "Ha riempito il suo bicchiere con succo.",
      "glass.jpeg",
      "/bitˈkjɛre/",
      { 12: 14, 19: 28 },
    ],
    [
      "l'erba",
      "I bambini stavano giocando nell'erba.",
      "grass.jpeg",
      "/ˈɛrba/",
      { 27: 37 },
    ],
    [
      "la mano",
      "Teneva delicatamente la mano del bambino.",
      "hand.jpeg",
      "/ˈmano/",
      { 21: 23, 24: 28 },
    ],
    [
      "la casa",
      "La casa era silenziosa.",
      "house.jpeg",
      "/ˈkaza/",
      { 0: 2, 3: 7 },
    ],
    [
      "la chiave",
      "Ha perso la chiave della sua macchina.",
      "key.jpeg",
      "/ˈkjaːve/",
      { 9: 11, 12: 18 },
    ],
    [
      "la luce",
      "C'era luce che entrava dalla finestra.",
      "light.jpeg",
      "/ˈlutʃe/",
      { 6: 10 },
    ],
    [
      "i soldi",
      "Ha risparmiato tutti i soldi che poteva.",
      "money.jpeg",
      "/ˈsoldi/",
      { 21: 22, 23: 28 },
    ],
    [
      "la luna",
      "La luna brillava intensamente nel cielo notturno.",
      "moon.jpeg",
      "/ˈluna/",
      { 0: 2, 3: 7 },
    ],
    [
      "la montagna",
      "Hanno scalato la montagna insieme.",
      "mountain.jpeg",
      "/monˈtaɲɲa/",
      { 14: 16, 17: 25 },
    ],
    [
      "la carta",
      "Ha scritto un appunto sulla carta.",
      "paper.jpeg",
      "/ˈkarta/",
      { 28: 34 },
    ],
    [
      "la matita",
      "Ha temperato la matita prima di iniziare il suo disegno.",
      "pencil.jpeg",
      "/maˈtita/",
      { 13: 15, 16: 22 },
    ],
    [
      "il telefono",
      "Il telefono ha squillato nel bel mezzo della notte.",
      "phone.jpeg",
      "/teˈlɛfono/",
      { 0: 2, 3: 11 },
    ],
    [
      "la fotografia",
      "La fotografia ha riportato molti ricordi.",
      "photograph.jpeg",
      "/fotoˈɡrafia/",
      { 0: 2, 3: 13 },
    ],
    [
      "il piatto",
      "Ha lavato il piatto e lo ha rimesso sullo scaffale.",
      "plate.jpeg",
      "/ˈpjatto/",
      { 10: 12, 13: 19 },
    ],
    [
      "il fiume",
      "Hanno seguito il fiume finché non hanno raggiunto un piccolo villaggio.",
      "river.jpeg",
      "/ˈfjume/",
      { 14: 16, 17: 22 },
    ],
    [
      "la strada",
      "La strada era dissestata e piena di buche.",
      "road.jpeg",
      "/'strada/",
      { 0: 2, 3: 9 },
    ],
    [
      "la scarpa",
      "Ha allacciato i lacci della sua scarpa.",
      "shoe.jpeg",
      "/ˈskarpa/",
      { 32: 39 },
    ],
    [
      "il cielo",
      "Il cielo era pieno di nuvole.",
      "sky.jpeg",
      "/ˈtʃɛːlo/",
      { 0: 2, 3: 8 },
    ],
    [
      "il tavolo",
      "Ha apparecchiato il tavolo per la cena.",
      "table.jpeg",
      "/ˈtavolo/",
      { 17: 19, 20: 26 },
    ],
    [
      "il treno",
      "Il treno è arrivato alla stazione puntuale.",
      "train.jpeg",
      "/ˈtrɛno/",
      { 0: 2, 3: 8 },
    ],
    [
      "l'albero",
      "L'albero offriva ombra nel sole caldo.",
      "tree.jpeg",
      "/ˈalbero/",
      { 0: 8 },
    ],
    [
      "l'orologio (da polso)",
      "Guardò il suo orologio da polso e si rese conto che era in ritardo.",
      "watch.jpeg",
      "/oroˈlodʒo/",
      { 7: 9, 14: 22 },
    ],
    [
      "l'acqua",
      "Ha bevuto l'acqua velocemente.",
      "water.jpeg",
      "/ˈakwa/",
      { 10: 17 },
    ],
    [
      "la finestra",
      "Ha aperto la finestra per far entrare un po' d'aria fresca.",
      "window.jpeg",
      "/fiˈnestra/",
      { 10: 12, 13: 21 },
    ],
  ];

const newVocabSet = generateVocabSet({ vocabEntries });

Object.assign(commonNounsIT, newVocabSet);
