import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsIT: VocabSetRaw = [
  [
    "l'aereo",
    "L'aereo volava alto sopra le nuvole.",
    "commonNouns/airplane.jpeg",
    "/aˈɛːreo/",
    { 0: 7 },
  ],
  [
    "il bambino",
    "Il bambino ha sorriso a sua madre.",
    "commonNouns/baby.jpeg",
    "/bamˈbiːno/",
    { 0: 2, 3: 10 },
  ],
  [
    "la palla",
    "Giovanni ha calciato la palla verso la porta.",
    "commonNouns/ball.jpeg",
    "/ˈpalla/",
    { 21: 23, 24: 29 },
  ],
  [
    "la spiaggia",
    "Stiamo pianificando di passare la giornata in spiaggia.",
    "commonNouns/beach.jpeg",
    "/ˈspjaddʒa/",
    { 46: 55 },
  ],
  [
    "il letto",
    "Si sdraiò sul suo letto, esausta dalla giornata.",
    "commonNouns/bed.jpeg",
    "/ˈletto/",
    { 18: 24 },
  ],
  [
    "la bicicletta",
    "Ha girato attorno al parco con la bicicletta.",
    "commonNouns/bicycle.jpeg",
    "/bitʃiˈkletta/",
    { 31: 33, 34: 45 },
  ],
  [
    "l'uccello",
    "L'uccello cantava splendidamente dal suo posatoio sull'albero.",
    "commonNouns/bird.jpeg",
    "/utˈtʃɛllo/",
    { 0: 9 },
  ],
  [
    "la barca",
    "Hanno navigato sul fiume con la barca.",
    "commonNouns/boat.jpeg",
    "/ˈbarka/",
    { 29: 31, 32: 38 },
  ],
  [
    "il libro",
    "Ha aperto il libro e ha cominciato a leggere.",
    "commonNouns/book.jpeg",
    "/ˈlibro/",
    { 10: 12, 13: 18 },
  ],
  [
    "la bottiglia",
    "Ho riempito la bottiglia con acqua di sorgente fresca.",
    "commonNouns/bottle.jpeg",
    "/botˈtiʎʎa/",
    { 12: 14, 15: 24 },
  ],
  [
    "il pane",
    "Ha tagliato il pane per la colazione.",
    "commonNouns/bread.jpeg",
    "/ˈpane/",
    { 12: 14, 15: 19 },
  ],
  [
    "la macchina fotografica",
    "Ha scattato una foto del bellissimo paesaggio con la sua macchina fotografica.",
    "commonNouns/camera.jpeg",
    "/ˌmak'kina fotoˈɡraːfika/",
    { 50: 52, 57: 65, 66: 78 },
  ],
  [
    "la macchina",
    "La macchina si è rotta lungo il percorso per l'ufficio.",
    "commonNouns/car.jpeg",
    "/makˈkina/",
    { 0: 2, 3: 11 },
  ],
  [
    "il gatto",
    "Il gatto dormiva sul divano.",
    "commonNouns/cat.jpeg",
    "/ˈɡatto/",
    { 0: 2, 3: 8 },
  ],
  [
    "la sedia",
    "Ha tirato fuori la sedia e si è seduto.",
    "commonNouns/chair.jpeg",
    "/ˈsɛdja/",
    { 16: 18, 19: 24 },
  ],
  [
    "l'orologio",
    "L'orologio segnava la mezzanotte.",
    "commonNouns/clock.jpeg",
    "/oroloˈdʒo/",
    { 0: 10 },
  ],
  [
    "i vestiti",
    "Ha piegato i vestiti e li ha messi via.",
    "commonNouns/clothes.jpeg",
    "/veˈstiti/",
    { 11: 12, 13: 20 },
  ],
  [
    "il computer",
    "Ha acceso il computer per iniziare il suo lavoro.",
    "commonNouns/computer.jpeg",
    "/komˈpjuter/",
    { 10: 12, 13: 21 },
  ],
  [
    "il cane",
    "Il cane scodinzolava felicemente.",
    "commonNouns/dog.jpeg",
    "/ˈkane/",
    { 0: 2, 3: 7 },
  ],
  ["la porta", "Ha bussato alla porta.", "door.jpeg", "/ˈporta/", { 16: 22 }],
  [
    "la fattoria",
    "Hanno trascorso la giornata lavorando alla fattoria.",
    "commonNouns/farm.jpeg",
    "/fattoˈria/",
    { 43: 52 },
  ],
  [
    "il pesce",
    "Il pesce nuotava velocemente nell'acqua chiara.",
    "commonNouns/fish.jpeg",
    "/ˈpeʃʃe/",
    { 0: 2, 3: 8 },
  ],
  [
    "il fiore",
    "Il fiore sbocciava splendidamente nel giardino.",
    "commonNouns/flower.jpeg",
    "/ˈfjore/",
    { 0: 2, 3: 8 },
  ],
  [
    "il cibo",
    "Il cibo aveva un profumo delizioso.",
    "commonNouns/food.jpeg",
    "/ˈtʃibo/",
    { 0: 2, 3: 7 },
  ],
  [
    "la foresta",
    "Sono andati a fare un'escursione nella foresta.",
    "commonNouns/forest.jpeg",
    "/forˈesta/",
    { 39: 47 },
  ],
  [
    "il giardino",
    "Stava sarchiando nel giardino.",
    "commonNouns/garden.jpeg",
    "/dʒarˈdino/",
    { 21: 30 },
  ],
  [
    "il bicchiere",
    "Ha riempito il suo bicchiere con succo.",
    "commonNouns/glass.jpeg",
    "/bitˈkjɛre/",
    { 12: 14, 19: 28 },
  ],
  [
    "l'erba",
    "I bambini stavano giocando nell'erba.",
    "commonNouns/grass.jpeg",
    "/ˈɛrba/",
    { 27: 37 },
  ],
  [
    "la mano",
    "Teneva delicatamente la mano del bambino.",
    "commonNouns/hand.jpeg",
    "/ˈmano/",
    { 21: 23, 24: 28 },
  ],
  [
    "la casa",
    "La casa era silenziosa.",
    "commonNouns/house.jpeg",
    "/ˈkaza/",
    { 0: 2, 3: 7 },
  ],
  [
    "la chiave",
    "Ha perso la chiave della sua macchina.",
    "commonNouns/key.jpeg",
    "/ˈkjaːve/",
    { 9: 11, 12: 18 },
  ],
  [
    "la luce",
    "C'era luce che entrava dalla finestra.",
    "commonNouns/light.jpeg",
    "/ˈlutʃe/",
    { 6: 10 },
  ],
  [
    "i soldi",
    "Ha risparmiato tutti i soldi che poteva.",
    "commonNouns/money.jpeg",
    "/ˈsoldi/",
    { 21: 22, 23: 28 },
  ],
  [
    "la luna",
    "La luna brillava intensamente nel cielo notturno.",
    "commonNouns/moon.jpeg",
    "/ˈluna/",
    { 0: 2, 3: 7 },
  ],
  [
    "la montagna",
    "Hanno scalato la montagna insieme.",
    "commonNouns/mountain.jpeg",
    "/monˈtaɲɲa/",
    { 14: 16, 17: 25 },
  ],
  [
    "la carta",
    "Ha scritto un appunto sulla carta.",
    "commonNouns/paper.jpeg",
    "/ˈkarta/",
    { 28: 34 },
  ],
  [
    "la matita",
    "Ha temperato la matita prima di iniziare il suo disegno.",
    "commonNouns/pencil.jpeg",
    "/maˈtita/",
    { 13: 15, 16: 22 },
  ],
  [
    "il telefono",
    "Il telefono ha squillato nel bel mezzo della notte.",
    "commonNouns/phone.jpeg",
    "/teˈlɛfono/",
    { 0: 2, 3: 11 },
  ],
  [
    "la fotografia",
    "La fotografia ha riportato molti ricordi.",
    "commonNouns/photograph.jpeg",
    "/fotoˈɡrafia/",
    { 0: 2, 3: 13 },
  ],
  [
    "il piatto",
    "Ha lavato il piatto e lo ha rimesso sullo scaffale.",
    "commonNouns/plate.jpeg",
    "/ˈpjatto/",
    { 10: 12, 13: 19 },
  ],
  [
    "il fiume",
    "Hanno seguito il fiume finché non hanno raggiunto un piccolo villaggio.",
    "commonNouns/river.jpeg",
    "/ˈfjume/",
    { 14: 16, 17: 22 },
  ],
  [
    "la strada",
    "La strada era dissestata e piena di buche.",
    "commonNouns/road.jpeg",
    "/'strada/",
    { 0: 2, 3: 9 },
  ],
  [
    "la scarpa",
    "Ha allacciato i lacci della sua scarpa.",
    "commonNouns/shoe.jpeg",
    "/ˈskarpa/",
    { 32: 39 },
  ],
  [
    "il cielo",
    "Il cielo era pieno di nuvole.",
    "commonNouns/sky.jpeg",
    "/ˈtʃɛːlo/",
    { 0: 2, 3: 8 },
  ],
  [
    "il tavolo",
    "Ha apparecchiato il tavolo per la cena.",
    "commonNouns/table.jpeg",
    "/ˈtavolo/",
    { 17: 19, 20: 26 },
  ],
  [
    "il treno",
    "Il treno è arrivato alla stazione puntuale.",
    "commonNouns/train.jpeg",
    "/ˈtrɛno/",
    { 0: 2, 3: 8 },
  ],
  [
    "l'albero",
    "L'albero offriva ombra nel sole caldo.",
    "commonNouns/tree.jpeg",
    "/ˈalbero/",
    { 0: 8 },
  ],
  [
    "l'orologio (da polso)",
    "Guardò il suo orologio da polso e si rese conto che era in ritardo.",
    "commonNouns/watch.jpeg",
    "/oroˈlodʒo/",
    { 7: 9, 14: 22 },
  ],
  [
    "l'acqua",
    "Ha bevuto l'acqua velocemente.",
    "commonNouns/water.jpeg",
    "/ˈakwa/",
    { 10: 17 },
  ],
  [
    "la finestra",
    "Ha aperto la finestra per far entrare un po' d'aria fresca.",
    "commonNouns/window.jpeg",
    "/fiˈnestra/",
    { 10: 12, 13: 21 },
  ],
];
