import { generateVocabSet } from "@/lib/initialVocab";
import { Vocab } from "@/types/vocab";

export const commonNounsNL: { [vocabId: string]: Vocab } = {};

const vocabEntries: [string, string, string, string, Record<number, number>][] =
  [
    [
      "het vliegtuig",
      "Het vliegtuig vloog hoog boven de wolken.",
      "airplane.jpeg",
      "/ˈvlɛi̯xtœy̯x/",
      { 0: 3, 4: 13 },
    ],
    [
      "de baby",
      "De baby lachte naar haar moeder.",
      "baby.jpeg",
      "/ˈbeːbi/",
      { 0: 2, 3: 7 },
    ],
    [
      "de bal",
      "John trapte de bal richting het doel.",
      "ball.jpeg",
      "/bɑl/",
      { 12: 14, 15: 18 },
    ],
    [
      "het strand",
      "We zijn van plan de dag op het strand door te brengen.",
      "beach.jpeg",
      "/strɑnt/",
      { 27: 30, 31: 37 },
    ],
    [
      "het bed",
      "Ze ging op haar bed liggen, uitgeput van de dag.",
      "bed.jpeg",
      "/bɛt/",
      { 16: 19 },
    ],
    [
      "de fiets",
      "Ik denk erover om een nieuwe fiets te kopen.",
      "bicycle.jpeg",
      "/ˈfits/",
      { 29: 34 },
    ],
    [
      "de vogel",
      "De vogel zong prachtig vanaf zijn plekje in de boom.",
      "bird.jpeg",
      "/ˈvoːxəl/",
      { 0: 2, 3: 8 },
    ],
    [
      "de boot",
      "Ze voeren de rivier af met de boot.",
      "boat.jpeg",
      "/bot/",
      { 27: 29, 30: 35 },
    ],
    [
      "het boek",
      "Ze opende het boek en begon te lezen.",
      "book.jpeg",
      "/buk/",
      { 10: 13, 14: 18 },
    ],
    [
      "de fles",
      "Ik vulde de fles met vers bronwater.",
      "bottle.jpeg",
      "/ˈflɛs/",
      { 9: 11, 12: 16 },
    ],
    [
      "het brood",
      "Ze sneed het brood voor het ontbijt.",
      "bread.jpeg",
      "/broːt/",
      { 9: 12, 13: 18 },
    ],
    [
      "de camera",
      "Hij nam een foto van het prachtige landschap met zijn camera.",
      "camera.jpeg",
      "/kaːˈmeːraː/",
      { 54: 61 },
    ],
    [
      "de auto",
      "De auto viel stil op weg naar kantoor.",
      "car.jpeg",
      "/ˈʔɑu̯toː/",
      { 0: 2, 3: 7 },
    ],
    [
      "de kat",
      "De kat lag te slapen op de bank.",
      "cat.jpeg",
      "/kɑt/",
      { 0: 2, 3: 6 },
    ],
    [
      "de stoel",
      "Hij schoof de stoel naar achteren en ging zitten.",
      "chair.jpeg",
      "/stuːl/",
      { 11: 13, 14: 19 },
    ],
    [
      "de klok",
      "De klok sloeg middernacht.",
      "clock.jpeg",
      "/klɔk/",
      { 0: 2, 3: 7 },
    ],
    [
      "de kleren",
      "Ze vouwde de kleren op en borg ze weg.",
      "clothes.jpeg",
      "/ˈkleːrə(n)/",
      { 10: 12, 13: 19 },
    ],
    [
      "de computer",
      "Hij zette de computer aan om aan zijn werk te beginnen.",
      "computer.jpeg",
      "/kɔmˈpyːtər/",
      { 10: 12, 13: 21 },
    ],
    [
      "de hond",
      "De hond kwispelde vrolijk met zijn staart.",
      "dog.jpeg",
      "/ɦɔnt/",
      { 0: 2, 3: 7 },
    ],
    [
      "de deur",
      "Hij klopte op de deur.",
      "door.jpeg",
      "/dør/",
      { 14: 16, 17: 22 },
    ],
    [
      "de boerderij",
      "Ze brachten de dag door met werken op de boerderij.",
      "farm.jpeg",
      "/ˈburdərɛi̯/",
      { 38: 40, 41: 51 },
    ],
    [
      "de vis",
      "De vis zwom snel in het heldere water.",
      "fish.jpeg",
      "/fɪs/",
      { 0: 2, 3: 6 },
    ],
    [
      "de bloem",
      "De bloem bloeide prachtig in de tuin.",
      "flower.jpeg",
      "/blum/",
      { 0: 2, 3: 8 },
    ],
    [
      "het eten",
      "Het eten rook heerlijk.",
      "food.jpeg",
      "/ˈeːtə(n)/",
      { 0: 3, 4: 8 },
    ],
    [
      "het bos",
      "Ze gingen wandelen in het bos.",
      "forest.jpeg",
      "/bɔs/",
      { 22: 25, 26: 30 },
    ],
    [
      "de tuin",
      "Ze was aan het wieden in de tuin.",
      "garden.jpeg",
      "/ˈtœy̯n/",
      { 25: 27, 28: 33 },
    ],
    [
      "het glas",
      "Hij vulde zijn glas met sap.",
      "glass.jpeg",
      "/xlɑs/",
      { 15: 19 },
    ],
    [
      "het gras",
      "De kinderen speelden in het gras.",
      "grass.jpeg",
      "/xrɑs/",
      { 24: 27, 28: 33 },
    ],
    [
      "de hand",
      "Ze hield de hand van de baby zachtjes vast.",
      "hand.jpeg",
      "/ɦɑnt/",
      { 9: 11, 12: 16 },
    ],
    ["het huis", "Het huis was stil.", "house.jpeg", "/ɦœys/", { 0: 3, 4: 8 }],
    [
      "de sleutel",
      "Hij verloor de sleutel van zijn auto.",
      "key.jpeg",
      "/ˈsløːtəl/",
      { 12: 14, 15: 22 },
    ],
    [
      "het licht",
      "Er kwam licht binnen van het raam.",
      "light.jpeg",
      "/lɪxt/",
      { 8: 13 },
    ],
    [
      "het geld",
      "Hij spaarde al het geld dat hij kon.",
      "money.jpeg",
      "/ɣɛlt/",
      { 15: 18, 19: 23 },
    ],
    [
      "de maan",
      "De maan scheen fel in de nachtelijke hemel.",
      "moon.jpeg",
      "/maːn/",
      { 0: 2, 3: 7 },
    ],
    [
      "de berg",
      "Ze beklommen samen de berg.",
      "mountain.jpeg",
      "/bɛrɣ/",
      { 19: 21, 22: 27 },
    ],
    [
      "het papier",
      "Hij schreef een notitie op het papier.",
      "paper.jpeg",
      "/pɑˈpir/",
      { 27: 30, 31: 38 },
    ],
    [
      "het potlood",
      "Ze slijpte haar potlood voordat ze haar tekening begon.",
      "pencil.jpeg",
      "/ˈpɔtloːt/",
      { 16: 23 },
    ],
    [
      "de telefoon",
      "De telefoon ging midden in de nacht over.",
      "phone.jpeg",
      "/təˈleːfɔn/",
      { 0: 2, 3: 11 },
    ],
    [
      "de foto",
      "De foto bracht veel herinneringen terug.",
      "photograph.jpeg",
      "/ˈfotoː/",
      { 0: 2, 3: 7 },
    ],
    [
      "het bord",
      "Hij waste het bord en zette het terug op de plank.",
      "plate.jpeg",
      "/bɔrt/",
      { 10: 13, 14: 18 },
    ],
    [
      "de rivier",
      "Ze volgden de rivier totdat ze een klein dorpje bereikten.",
      "river.jpeg",
      "/ˈriːviːr/",
      { 11: 13, 14: 20 },
    ],
    [
      "de weg",
      "De weg was hobbelig en vol kuilen.",
      "road.jpeg",
      "/ʋeːx/",
      { 0: 2, 3: 6 },
    ],
    [
      "de schoen",
      "Hij strikte de veters van zijn schoen.",
      "shoe.jpeg",
      "/sχun/",
      { 31: 38 },
    ],
    [
      "de lucht",
      "De lucht zat vol met wolken.",
      "sky.jpeg",
      "/lʏxt/",
      { 0: 2, 3: 8 },
    ],
    [
      "de tafel",
      "Ze dekte de tafel voor het avondeten.",
      "table.jpeg",
      "/ˈtaːfəl/",
      { 9: 11, 12: 17 },
    ],
    [
      "de trein",
      "De trein kwam op tijd aan bij het station.",
      "train.jpeg",
      "/treːn/",
      { 0: 2, 3: 8 },
    ],
    [
      "de boom",
      "De boom bood schaduw in de hete zon.",
      "tree.jpeg",
      "/boːm/",
      { 0: 2, 3: 7 },
    ],
    [
      "het horloge",
      "Hij keek op zijn horloge en besefte dat hij laat was.",
      "watch.jpeg",
      "/ˈɦɔrloːɣə/",
      { 17: 24 },
    ],
    [
      "het water",
      "Ze dronk het water snel op.",
      "water.jpeg",
      "/ˈʋaːtər/",
      { 9: 12, 13: 18 },
    ],
    [
      "het raam",
      "Hij opende het raam om wat frisse lucht binnen te laten.",
      "window.jpeg",
      "/raːm/",
      { 11: 14, 15: 19 },
    ],
  ];

const newVocabSet = generateVocabSet({ vocabEntries });

Object.assign(commonNounsNL, newVocabSet);
