import { VocabSetRaw } from "@/lib/vocab";

export const commonNounsNL: VocabSetRaw = [
  [
    "het vliegtuig",
    "Het vliegtuig vloog hoog boven de wolken.",
    "commonNouns/airplane.jpeg",
    "/ˈvlɛi̯xtœy̯x/",
    { 0: 3, 4: 13 },
  ],
  [
    "de baby",
    "De baby lachte naar haar moeder.",
    "commonNouns/baby.jpeg",
    "/ˈbeːbi/",
    { 0: 2, 3: 7 },
  ],
  [
    "de bal",
    "John trapte de bal richting het doel.",
    "commonNouns/ball.jpeg",
    "/bɑl/",
    { 12: 14, 15: 18 },
  ],
  [
    "het strand",
    "We zijn van plan de dag op het strand door te brengen.",
    "commonNouns/beach.jpeg",
    "/strɑnt/",
    { 27: 30, 31: 37 },
  ],
  [
    "het bed",
    "Ze ging op haar bed liggen, uitgeput van de dag.",
    "commonNouns/bed.jpeg",
    "/bɛt/",
    { 16: 19 },
  ],
  [
    "de fiets",
    "Ik denk erover om een nieuwe fiets te kopen.",
    "commonNouns/bicycle.jpeg",
    "/ˈfits/",
    { 29: 34 },
  ],
  [
    "de vogel",
    "De vogel zong prachtig vanaf zijn plekje in de boom.",
    "commonNouns/bird.jpeg",
    "/ˈvoːxəl/",
    { 0: 2, 3: 8 },
  ],
  [
    "de boot",
    "Ze voeren de rivier af met de boot.",
    "commonNouns/boat.jpeg",
    "/bot/",
    { 27: 29, 30: 35 },
  ],
  [
    "het boek",
    "Ze opende het boek en begon te lezen.",
    "commonNouns/book.jpeg",
    "/buk/",
    { 10: 13, 14: 18 },
  ],
  [
    "de fles",
    "Ik vulde de fles met vers bronwater.",
    "commonNouns/bottle.jpeg",
    "/ˈflɛs/",
    { 9: 11, 12: 16 },
  ],
  [
    "het brood",
    "Ze sneed het brood voor het ontbijt.",
    "commonNouns/bread.jpeg",
    "/broːt/",
    { 9: 12, 13: 18 },
  ],
  [
    "de camera",
    "Hij nam een foto van het prachtige landschap met zijn camera.",
    "commonNouns/camera.jpeg",
    "/kaːˈmeːraː/",
    { 54: 61 },
  ],
  [
    "de auto",
    "De auto viel stil op weg naar kantoor.",
    "commonNouns/car.jpeg",
    "/ˈʔɑu̯toː/",
    { 0: 2, 3: 7 },
  ],
  [
    "de kat",
    "De kat lag te slapen op de bank.",
    "commonNouns/cat.jpeg",
    "/kɑt/",
    { 0: 2, 3: 6 },
  ],
  [
    "de stoel",
    "Hij schoof de stoel naar achteren en ging zitten.",
    "commonNouns/chair.jpeg",
    "/stuːl/",
    { 11: 13, 14: 19 },
  ],
  [
    "de klok",
    "De klok sloeg middernacht.",
    "commonNouns/clock.jpeg",
    "/klɔk/",
    { 0: 2, 3: 7 },
  ],
  [
    "de kleren",
    "Ze vouwde de kleren op en borg ze weg.",
    "commonNouns/clothes.jpeg",
    "/ˈkleːrə(n)/",
    { 10: 12, 13: 19 },
  ],
  [
    "de computer",
    "Hij zette de computer aan om aan zijn werk te beginnen.",
    "commonNouns/computer.jpeg",
    "/kɔmˈpyːtər/",
    { 10: 12, 13: 21 },
  ],
  [
    "de hond",
    "De hond kwispelde vrolijk met zijn staart.",
    "commonNouns/dog.jpeg",
    "/ɦɔnt/",
    { 0: 2, 3: 7 },
  ],
  [
    "de deur",
    "Hij klopte op de deur.",
    "commonNouns/door.jpeg",
    "/dør/",
    { 14: 16, 17: 22 },
  ],
  [
    "de boerderij",
    "Ze brachten de dag door met werken op de boerderij.",
    "commonNouns/farm.jpeg",
    "/ˈburdərɛi̯/",
    { 38: 40, 41: 51 },
  ],
  [
    "de vis",
    "De vis zwom snel in het heldere water.",
    "commonNouns/fish.jpeg",
    "/fɪs/",
    { 0: 2, 3: 6 },
  ],
  [
    "de bloem",
    "De bloem bloeide prachtig in de tuin.",
    "commonNouns/flower.jpeg",
    "/blum/",
    { 0: 2, 3: 8 },
  ],
  [
    "het eten",
    "Het eten rook heerlijk.",
    "commonNouns/food.jpeg",
    "/ˈeːtə(n)/",
    { 0: 3, 4: 8 },
  ],
  [
    "het bos",
    "Ze gingen wandelen in het bos.",
    "commonNouns/forest.jpeg",
    "/bɔs/",
    { 22: 25, 26: 30 },
  ],
  [
    "de tuin",
    "Ze was aan het wieden in de tuin.",
    "commonNouns/garden.jpeg",
    "/ˈtœy̯n/",
    { 25: 27, 28: 33 },
  ],
  [
    "het glas",
    "Hij vulde zijn glas met sap.",
    "commonNouns/glass.jpeg",
    "/xlɑs/",
    { 15: 19 },
  ],
  [
    "het gras",
    "De kinderen speelden in het gras.",
    "commonNouns/grass.jpeg",
    "/xrɑs/",
    { 24: 27, 28: 33 },
  ],
  [
    "de hand",
    "Ze hield de hand van de baby zachtjes vast.",
    "commonNouns/hand.jpeg",
    "/ɦɑnt/",
    { 9: 11, 12: 16 },
  ],
  ["het huis", "Het huis was stil.", "house.jpeg", "/ɦœys/", { 0: 3, 4: 8 }],
  [
    "de sleutel",
    "Hij verloor de sleutel van zijn auto.",
    "commonNouns/key.jpeg",
    "/ˈsløːtəl/",
    { 12: 14, 15: 22 },
  ],
  [
    "het licht",
    "Er kwam licht binnen van het raam.",
    "commonNouns/light.jpeg",
    "/lɪxt/",
    { 8: 13 },
  ],
  [
    "het geld",
    "Hij spaarde al het geld dat hij kon.",
    "commonNouns/money.jpeg",
    "/ɣɛlt/",
    { 15: 18, 19: 23 },
  ],
  [
    "de maan",
    "De maan scheen fel in de nachtelijke hemel.",
    "commonNouns/moon.jpeg",
    "/maːn/",
    { 0: 2, 3: 7 },
  ],
  [
    "de berg",
    "Ze beklommen samen de berg.",
    "commonNouns/mountain.jpeg",
    "/bɛrɣ/",
    { 19: 21, 22: 27 },
  ],
  [
    "het papier",
    "Hij schreef een notitie op het papier.",
    "commonNouns/paper.jpeg",
    "/pɑˈpir/",
    { 27: 30, 31: 38 },
  ],
  [
    "het potlood",
    "Ze slijpte haar potlood voordat ze haar tekening begon.",
    "commonNouns/pencil.jpeg",
    "/ˈpɔtloːt/",
    { 16: 23 },
  ],
  [
    "de telefoon",
    "De telefoon ging midden in de nacht over.",
    "commonNouns/phone.jpeg",
    "/təˈleːfɔn/",
    { 0: 2, 3: 11 },
  ],
  [
    "de foto",
    "De foto bracht veel herinneringen terug.",
    "commonNouns/photograph.jpeg",
    "/ˈfotoː/",
    { 0: 2, 3: 7 },
  ],
  [
    "het bord",
    "Hij waste het bord en zette het terug op de plank.",
    "commonNouns/plate.jpeg",
    "/bɔrt/",
    { 10: 13, 14: 18 },
  ],
  [
    "de rivier",
    "Ze volgden de rivier totdat ze een klein dorpje bereikten.",
    "commonNouns/river.jpeg",
    "/ˈriːviːr/",
    { 11: 13, 14: 20 },
  ],
  [
    "de weg",
    "De weg was hobbelig en vol kuilen.",
    "commonNouns/road.jpeg",
    "/ʋeːx/",
    { 0: 2, 3: 6 },
  ],
  [
    "de schoen",
    "Hij strikte de veters van zijn schoen.",
    "commonNouns/shoe.jpeg",
    "/sχun/",
    { 31: 38 },
  ],
  [
    "de lucht",
    "De lucht zat vol met wolken.",
    "commonNouns/sky.jpeg",
    "/lʏxt/",
    { 0: 2, 3: 8 },
  ],
  [
    "de tafel",
    "Ze dekte de tafel voor het avondeten.",
    "commonNouns/table.jpeg",
    "/ˈtaːfəl/",
    { 9: 11, 12: 17 },
  ],
  [
    "de trein",
    "De trein kwam op tijd aan bij het station.",
    "commonNouns/train.jpeg",
    "/treːn/",
    { 0: 2, 3: 8 },
  ],
  [
    "de boom",
    "De boom bood schaduw in de hete zon.",
    "commonNouns/tree.jpeg",
    "/boːm/",
    { 0: 2, 3: 7 },
  ],
  [
    "het horloge",
    "Hij keek op zijn horloge en besefte dat hij laat was.",
    "commonNouns/watch.jpeg",
    "/ˈɦɔrloːɣə/",
    { 17: 24 },
  ],
  [
    "het water",
    "Ze dronk het water snel op.",
    "commonNouns/water.jpeg",
    "/ˈʋaːtər/",
    { 9: 12, 13: 18 },
  ],
  [
    "het raam",
    "Hij opende het raam om wat frisse lucht binnen te laten.",
    "commonNouns/window.jpeg",
    "/raːm/",
    { 11: 14, 15: 19 },
  ],
];
